### ISSUE TITLE
New 'System' appearance theme does not respect System theme

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#10]
Hey thanks for the feature rich update.

It seems the System appearance mode is always using Light mode despite what the system theme is.

**Comment by longseespace** [comment]
Oh you're right. Will fix in the next version.

**Comment by longseespace** [comment]
Added in v1.12: https://boltai.com/changelogs/v1.12

Feel free to reopen the ticket if it doesn't work :D
