### ISSUE TITLE
Enter to send message broken in 1.16.0 

### ISSUE THREAD

**Issue by MichaelPietroforte** [BoltAI/BoltAI#100]
Version 1.16.0 appears to have a significant bug. The _Enter to send message_ feature frequently fails. When I press enter, the message vanishes instead of being sent. Restarting the app usually resolves the issue temporarily. The _Send message_ icon functions correctly at all times.

**Comment by longseespace** [comment]
Can you update to v1.16.1 and try again. Sorry for the issue

**Comment by MichaelPietroforte** [comment]
It seems to work now. Thanks for the swift update!

**Comment by rb81** [comment]
@longseespace This seems to still be a problem even with the latest release.
