### ISSUE TITLE
icon and acknowledgements

### ISSUE THREAD

**Issue by Zoge13** [BoltAI/BoltAI#101]
There are two little bugs in the app
1- The icon will not be changed after I close the app; it only works when the application is opened.   
2- in settings  ==> advanced tab, when I click on the acknowledgments, there is no way to close the window. It will stuck in that window.

https://github.com/BoltAI/BoltAI/assets/119809710/29bc2bd8-f25c-4222-a815-62ca198b6e75

**Comment by longseespace** [comment]
Hi. I've fixed the App Icon issue in `v1.16.2`. You might need to re-open the app a couple of times.

Thanks
