### ISSUE TITLE
After paying to upgrade, a little annoying to find out plugin memory doesn't last with new chats

### ISSUE THREAD

**Issue by bwt615** [BoltAI/BoltAI#102]
I'd add call outs to your highest paying product. That was the expectation i came in with.

**Comment by longseespace** [comment]
What do you mean “plugin memory”?

**Comment by bwt615** [comment]
Even with remember settings for all chats, I still need to re enable Apple script, terminal etc

**Comment by longseespace** [comment]
Ah I see. Sorry for the issue. 

I'm re-working the feature "remember settings for all chats" as many users do not want to remember all settings and only part of it (some people want only the AI service/model configuration, some people want all configurations).

I think it should remember all settings, but I need to support other cases too.

I will fix this soon.

**Comment by bwt615** [comment]
Thank you! Maybe for each plugin add a toggle enable by default?

Trying to think of a quick win on this - feel a lot of people might not feel it’s actually “unlimited” plugins - rather unlimited if you remember to turn on**

[Benjamin Thomas]
Benjamin Thomas
Mobile: +1 (781) 864-3648 | Fax: +1 (781) 787-2609
Email: ***@***.******@***.***> | Book: My Calendar<http://book.bthomas.io/> | Website: BThomas.io<http://bthomas.io/>
Twitter: @benjaminwthomas<https://twitter.com/benjaminwthomas> | LinkedIn: benjaminwesleythomas<https://www.linkedin.com/in/benjaminwesleythomas/>
________________________________

**Comment by longseespace** [comment]
I've fixed this in `v1.16.2`. When using `remember settings for all chats` setting, it should remember your choice of plugins. Can you confirm @bwt615. Thanks

**Comment by bwt615** [comment]
You rock, as always. We need to have a catch up as I think I could be fountain of feedback for you! Basically could be interested in doing a corporate deployment

**Comment by longseespace** [comment]
That would be great. My plan for this year is to offer the team version of BoltAI. Your feedback would greatly help!

Shoot me an email whenever you're free: daniel@boltai.com
