### ISSUE TITLE
Unusual Token Usages

### ISSUE THREAD

**Issue by xueyixingbang** [BoltAI/BoltAI#104]
<img width="1498" alt="iShot_2024-06-12_14 11 59" src="https://github.com/BoltAI/BoltAI/assets/7255878/a9df5f78-0847-4295-9d67-c9a1a9b4fa14">

I'm guessing the system automatically submitted all the context information? 
<img width="1555" alt="iShot_2024-06-12_14 16 52" src="https://github.com/BoltAI/BoltAI/assets/7255878/a4ae332b-8b26-4101-a358-7ff4e740f88c">

**Comment by longseespace** [comment]
It depends on the Context Limit setting in your Chat Configuration > Advanced. By default it uses the last 10 messages as context.

You can set it to 1 message to reduce costs but then the AI answers might not be accurate

**Comment by xueyixingbang** [comment]
> It depends on the Context Limit setting in your Chat Configuration > Advanced. By default it uses the last 10 messages as context.
> 
> You can set it to 1 message to reduce costs but then the AI answers might not be accurate

I've been using BoltAI heavily. 
The context window is normally 3-4. (I have double checked)
So I guess there is a bug.

**Comment by longseespace** [comment]
Oh you might be right. I recently disabled the default token check since it wasn’t always accurate. I’m taking a deeper look now. 

Sorry for the issue

**Comment by longseespace** [comment]
I've fixed this in `v1.16.2`. Please update.

Sorry again for the issue.
