### ISSUE TITLE
OpenAI Tools Issue with Latest Build

### ISSUE THREAD

**Issue by bwt615** [BoltAI/BoltAI#105]
![CleanShot 2024-06-12 at 10 42 56@2x](https://github.com/BoltAI/BoltAI/assets/48396397/a7d39d77-c89a-462f-9cb5-2181a0acac90)

**Comment by longseespace** [comment]
Can you help me reproduce this issue.

**Comment by bwt615** [comment]
sorry, i had to screenshot as you can't copy and paste error messages (you might want to fix that to make these easier to report).

![CleanShot 2024-06-12 at 11 03 05@2x](https://github.com/BoltAI/BoltAI/assets/48396397/61a23c67-c03d-49b6-95ea-a169588adc8d)

**Comment by yunapotamus** [comment]
This is happening to me, too. I have tried ChatGPT 3.5 Turbo, 4.0, and 4o. Same error message. This renders the app useless—please fix!

**Comment by yunapotamus** [comment]
I notice that new chats work properly. So I suspect that a repro is to open a chat thread that was created prior to this update, and issue a chat message.

Even though there's a workaround, this is still a high-priority bug, as it's not reasonable to expect users to have to re-create all their content because of a version upgrade.

**Comment by longseespace** [comment]
Sorry for the issue. I've identified the bug and been working on the fix. I will release a new version soon.

**Comment by longseespace** [comment]
I've released v1.16.4 with the fix. Please update.

I also added the page to download older versions of BoltAI: https://docs.boltai.com/docs/troubleshooting/download-previous-versions

Sorry again for the issue.

**Comment by yunapotamus** [comment]
Unfortunately, this is not fixed. I'm on v1.16.4 (build 83) and my chats still have this issue.

![OpenAI Error](https://github.com/BoltAI/BoltAI/assets/28821219/67c44d88-f954-4c37-a8b2-fd02a9685d05)

**Comment by yunapotamus** [comment]
Further investigation shows that any chat where I repro-ed this issue yesterday isn't fixed. New chats and chats where I didn't type in to trigger this issue are working. I hope this helps narrow it down.

**Comment by longseespace** [comment]
This is another issue and it only happens when you fork a chat with tool usage.

Unfortunately there is nothing I can do about this as the information about the tool calls has been lost.

Is's been fixed and new chats won't have this issue.
