### ISSUE TITLE
Unexpected keyboard shortcut behaviour on chat entry input focus

### ISSUE THREAD

**Issue by kyranjamie** [BoltAI/BoltAI#106]
<kbd>cmd</kbd> + <kbd>⌫</kbd> is normally delete entirely line, when in a text input, but now it prompts to delete the chat. 

I believe this behaviour should only be when the input isn't focused. Though perhaps tricky as you default to the input being focused. 

Perhaps:
- Case: When input focused and empty, Action: <kbd>cmd</kbd> + <kbd>⌫</kbd> deletes chat
- Case: When input is not focused, Action: <kbd>cmd</kbd> + <kbd>⌫</kbd> deletes chat
- Case: When input is focused and has text, Action: <kbd>cmd</kbd> + <kbd>⌫</kbd> deletes line

**Comment by longseespace** [comment]
Ah good idea. Maybe we can change it to `Command + Shift + Delete` to make it more explicit?

**Comment by longseespace** [comment]
I’ve changed it to Command Shift Delete
