### ISSUE TITLE
Submitted text gone

### ISSUE THREAD

**Issue by suntrop** [BoltAI/BoltAI#108]
I had put in a lot of text and when I hit enter my input was gone. Nothing else happened. The chat looked like I opened a new chat. This was especially frustrating because I put significant effort into my text. This is the next bug in BoltAI. It is all good and I like having a native app, but the bugs push me back to my previously used app :-/

**Comment by longseespace** [comment]
Sorry for the issue @suntrop. This was a bug in the underlying UI component and I've fixed it (if we're referring to the same bug). Can you confirm you're on the latest version of BoltAI? (this bug started in v1.6.0, I've fixed it in v1.6.2)

**Comment by longseespace** [comment]
Hello @suntrop 👋

**Comment by kyranjamie** [comment]
Came here to report the same, but see this issue exists. 

<img width="1012" alt="image" src="https://github.com/BoltAI/BoltAI/assets/1618764/c0601dbe-0b5a-4237-bf32-2ace30a9ebab">

Enter text. Text gone. Nothing happening. `V1.16.7`

**Comment by longseespace** [comment]
Ah very interesting. I never tested with the sidebar closed. Can you help me reproduce this issue. Did you hide the sidebar then start a new chat, or did you use the "Activate BoltAI" keyboard shortcut?

Anyway I could reproduce it?

Thanks

**Comment by kyranjamie** [comment]
It's happened to me before on earlier versions too, but only periodically. It seems like it happens after returning to Bolt after a period of it being open and not used. 

In trying to replicate (which I couldn't), I noticed some other strange behaviour with `cmd + n` create new page behaviour, when sidebar closed. Sometimes it creates a new chat in bg (which you can't see bc sidebar close), and it doesn't change focus to the new chat, it keeps focus on the old one.

**Comment by longseespace** [comment]
I can reproduce the `cmd + n` bug, working on the fix right now. I'm more interested in the first bug. Do you remember if it happened even with sidebar visible?

**Comment by kyranjamie** [comment]
Will report back if I can replicate again. I'm fairly sure I've experienced this with sidebar open too, though.

**Comment by longseespace** [comment]
I can replicate the `text gone` bug but only when the sidebar is closed. @kyranjamie do you remember when it happenned, was the loading spinner show up **before** you sending the message? (your screenshot above)

**Comment by kyranjamie** [comment]
Pretty sure the loading spinner only came up when I'd pressed enter, not before.

**Comment by longseespace** [comment]
I've released v1.16.8 trying to fix this bug. Please let me know if the issue still persists.

**Comment by longseespace** [comment]
I think it's solved. Can you confirm? Feel free to reopen the issue otherwise.
