### ISSUE TITLE
Large system instruction causes config popover to stretch very long

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#11]
When there is a very long system instruction, the chat config popover gets very large without constraints:

<img width="1416" alt="image" src="https://github.com/BoltAI/BoltAI/assets/77480421/400e3662-20b7-45d4-8145-54337118096a">

On a different, but related note, what causes the chat config popup button to be sluggish (regardless of system message)? There is almost always a 1-2 second delay between pressing it to bring it up or make it disappear (when clicking outside).

**Comment by longseespace** [comment]
Thank you. Didn't expect it to grow this wide 😅
