### ISSUE TITLE
Creating new chat puts it into a wrong folder.

### ISSUE THREAD

**Issue by Romportl** [BoltAI/BoltAI#110]
I have two folders: 1) Work, 2) Personal. I'm working with a chat that is inside Work folder. When I click on new chat icon, the new chat is created in Personal folder instead of Work. 

The expected behavior would be to open the new chat in the current folder being used (or selected).

**Comment by longseespace** [comment]
> When I click on new chat icon, the new chat is created in Personal folder instead of Work.

Actually it's in the `Root` folder but I see what you mean.

**Comment by longseespace** [comment]
I've fixed this in v1.16.7. Please update and confirm. Thanks
