### ISSUE TITLE
Paste action doesn't work with alternative keyboard layouts

### ISSUE THREAD

**Issue by neominik** [BoltAI/BoltAI#111]
Hi, thanks for creating this nice app! Since I am using a keyboard layout where basically all keys are relocated to other places (think dvorak or similar), anything that tries to paste stuff into applications (inline, global whisper, commands, …) fails, because instead of Cmd+V it will press Cmd+P in my case. 
In other places in the app (e.g., recording keyboard shortcuts in the settings) the correct mapping does work.
My current workaround for commands is to set all of them to "copy to clipboard" and then pasting manually, which is fine, but for the new global whisper or inline commands, this is not an option.
A fix for this would be much appreciated!

**Comment by longseespace** [comment]
Hey @neominik. Can you help me set up this custom layboard layout. How can I do it? Or does it require a physical keyboard with a different layout?

**Comment by neominik** [comment]
It shouldn't really matter which specific layout you use. There is also no need for a different physical keyboard (assuming you have an ISO or ANSI layout). You could try Dvorak, which is included in macOS. Add it as a new input method in System Settings -> Keyboard -> Input Sources -> + -> English - Dvorak. It has a 'k' in the place of 'v'.

Or if you want to try my specific layout, you can download it at https://dl.neo-layout.org/neo.keylayout (you might need to download an icon as well: https://dl.neo-layout.org/grafik/logos/neo.icns), then move the files to `/Library/Keyboard Layouts` (or `~/Library/Keyboard Layouts`). Then you can select it in the Input Sources under "Others" -> Neo.

I also recommend setting "Show input menu in menu bar" (Input Sources -> All Input Sources) for the duration of your experiments so you can easily switch between layouts and check which one is active.

Thanks for looking into this!

**Comment by longseespace** [comment]
I've fixed this in v1.21.0. Can you confirm? Sorry for the delay 😅

**Comment by neominik** [comment]
I tested it and it seems to work. Thank you very much!

**Comment by neominik** [comment]
Unfortunately, the fix didn't survive the v2 rewrite. Tested with version 2.2.0 (build 39). @longseespace, could you please port the fix to the rewrite? Thank you 🙏🏻

**Comment by longseespace** [comment]
Ah shoot. I totally forgot about this. I'm going to fix it soon.

**Comment by longseespace** [comment]
I've added it in v2.2.1. Can you try again?

**Comment by neominik** [comment]
Nice! Thanks for the lightning fast fix!
