### ISSUE TITLE
Perplexity Plugin Returns Despite Being Turned Off

### ISSUE THREAD

**Issue by rb81** [BoltAI/BoltAI#115]
I have chat the "Remember settings for all chats" turned on. If I turn on or off a plugin, the setting is remembered -- except with Perplexity. That always turns back on.

**Comment by longseespace** [comment]
I've fixed this in v1.16.7. Please update and confirm. Thanks

**Comment by rb81** [comment]
@longseespace - Confirmed. Latest release resolves this. Thanks so much!
