### ISSUE TITLE
Functions don't work with models that support functions ("AI plugins require function calling")

### ISSUE THREAD

**Issue by sammcj** [BoltAI/BoltAI#118]
When trying to use plugins/function calling with models that support it, bolt shows this error:

<img width="707" alt="SCR-20240702-pyer" src="https://github.com/BoltAI/BoltAI/assets/862951/b609a93b-03b0-4dea-b4fc-6644f7f7b6ee">

I've tried with:

- Command R Plus
- Llama 3
- Qwen 2

and a couple of others, on both:

- Ollama (local)
- Ollama (remote)
- OpenAI Compatible API (exllamav2 via/ TabbyAPI)
- Text Generation WebUI (exllamav2)

Is there a way to force enable plugins with models?

**Comment by longseespace** [comment]
Unfortunately there is no way to force enable plugins for a model yet.

Also, model's Function Calling capability is only half of the story. BoltAI currently requires the inference server to support OpenAI's tool use specs. Unfortunately, Ollama doesn't support this yet.
 
![CleanShot 2024-07-02 at 15 20 30@2x](https://github.com/BoltAI/BoltAI/assets/187720/51f3a3b1-6c12-4cee-a2eb-22e33456f1d7)

**Comment by sammcj** [comment]
Ah, I see thanks for explaining this Daniel!

Feel free to close the issue if you don't think it's likely to come to bolt any time soon, otherwise happy to leave it as-is for the future.
