### ISSUE TITLE
Gap between end of messages list scrollbar and chat input box start

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#12]
Very very minor one but there is a small gap between the end of the scrollbar and the start of the textfield. While this does not really bother me, this led me to wonder if you are using `.safeAreaInset` for adding the textfield below the messages view. This, by default adds a very similar gap. In case you are using this, would it be worthwhile checking out the `spacing` parameter of  `.safeAreaInset`? By default this modifier also adds a line of background color above the view inside, similar to some sort of system bg. This also led me to wonder if this was the reason the chat bg color was changed in the recent update.

<img width="136" alt="Screenshot 2023-11-05 at 3 29 56 AM" src="https://github.com/BoltAI/BoltAI/assets/77480421/424b29db-0d7e-4b7d-b678-314d709a0a67">

**Comment by longseespace** [comment]
Yes, I'm using `safeAreaInset`. I'm still unsure if it helps with scroll performance comparing to using VStack. Thanks, will fix in the next version!

**Comment by SilverMarcs** [comment]
Hmm, not sure if `safeAreaInset` by itself is able to improve scrolling. Why `VStack` though? Isn't putting `safeAreaInset` modifier itself to a `ScrollView` of chat messages a bit simpler?

In any case, would you consider reverting to the darker chat bg color?

As for scrolling, yeah a bit hard to measure effectively. It is still somewhat janky and not sure if better than prev version. Could  the markdown renderer be causing the lag? I have used `swift-markdown-ui` with `Splash` themes and the scrolling was still very smooth. Although, your app probably has a lot more going on in the chat messages area so could be something else too.

**Comment by longseespace** [comment]
@SilverMarcs I'm losing track. Which bg color were you referring to, 1 or 2?

![CleanShot 2023-12-02 at 12 30 25@2x](https://github.com/BoltAI/BoltAI/assets/187720/d326d3b0-8587-4040-b9b9-234a3c1fb847)

**Comment by longseespace** [comment]
Never mind. I think I figured it out. Is this what you want? I wasn't aware that it changed the chat background in dark mode :D

![CleanShot 2023-12-02 at 12 46 18@2x](https://github.com/BoltAI/BoltAI/assets/187720/7e0e16aa-04bf-453e-a30e-9f5d7c249c11)

**Comment by SilverMarcs** [comment]
Yeah your latest comment is the one. Looks nice!
