### ISSUE TITLE
When using ollama, BoltAI will send current time.

### ISSUE THREAD

**Issue by shinyypig** [BoltAI/BoltAI#120]
```
{
  "temperature": 0,
  "messages": [
    {
      "content": "You are an efficient translation assistant with the following requirements:\n\n- Non-Chinese -> Simplified Chinese\n- Simplified  Chinese -> English\n- Maintain the original structure and punctuation\n- Only provide the translation result\n\nPlease translate the text I provide in the following.\n\nCurrent time: Wednesday, July 3, 2024 at 10:55:33 China Standard Time.",
      "role": "system"
    },
    {
      "content": "保持原有的结构和标点符号",
      "role": "user"
    }
  ],
  "model": "llama3:latest",
  "stream": true
}
```

I managed to capture the request body send by boltai to ollama.

It can be found that the current time is attached in the content, which may cause chaos.

<img width="800" alt="image" src="https://github.com/BoltAI/BoltAI/assets/30233673/cb55db27-9d5e-4545-a4f6-c0ae41955c40">

Is there anyway I can disable it?

**Comment by shinyypig** [comment]
<img width="800" alt="image" src="https://github.com/BoltAI/BoltAI/assets/30233673/c4c3dacc-e7be-474c-bdf3-d5d384dbac82">

find it!

**Comment by longseespace** [comment]
Glad you solved it. I will add a small notice under the System Instruction in the next version :D
