### ISSUE TITLE
[FEATURE REQUEST] Export Settings or iCloud Sync

### ISSUE THREAD

**Issue by feassarian** [BoltAI/BoltAI#122]
One of the benefits of BoltAI is the granular level of customization you can setup for your use cases.

If you are using BoltAI on multiple devices - you may want to have those same settings on each device (maybe not, use case for both scenarios).

Either provide an export function to export a config file of the settings (prompts, maybe api keys, etc) or allow those settings to be sync'd via iCloud or similar.

**Comment by longseespace** [comment]
You can already export & import data in BoltAI. I wrote a short guide here: https://docs.boltai.com/docs/chat-ui/import-export

The iCloud sync feature is currently in development. Thanks

**Comment by feassarian** [comment]
Found an "Export BoltAI Data" button under Advanced -> Data Management
Unsure what all is included in this export - might include the original feature request - unknown though

**Comment by feassarian** [comment]
> You can already export & import data in BoltAI. I wrote a short guide here: https://docs.boltai.com/docs/chat-ui/import-export
> 
> The iCloud sync feature is currently in development. Thanks

Thanks for the quick response and the link...
