### ISSUE TITLE
DALL·E 3 plugin not really working

### ISSUE THREAD

**Issue by MichaelPietroforte** [BoltAI/BoltAI#125]
The images that the DALL·E 3 plugin creates are always useless and do not compare at all to the images produced by DALL·E 3 on the ChatGPT website. It appears to be a setting that is unavailable in BoltAI.

**Comment by longseespace** [comment]
While we don't know the actual implementation from OpenAI, BoltAI attempts to recreate the experience using their official APIs: GPT-4o and Dall E image generation. 

It's hard to compare the quality of the AI images if you don't provide a concrete example or a reproducible way to compare it.

**Comment by MichaelPietroforte** [comment]
>It's hard to compare the quality of the AI images if you don't provide a concrete example or a reproducible way to compare it.

It's actually very easy. The image quality achieved via the BoltAI plugin is 0%, whereas the web DALL·E produces results at 100%.

You can use any prompt, or try this one: "Create an image of 2 vectors with a small angel and a common initial point. One vector points to the word cat and the other vector points to the word tiger."

**Comment by longseespace** [comment]
Thanks. Can you share the images you generated and your expectation. And if possible, share some more examples.

This is what I got and from what I can see, ChatGPT is not 100% better.

ChatGPT app:
![CleanShot 2024-07-10 at 21 44 50@2x](https://github.com/BoltAI/BoltAI/assets/187720/6a209134-1d7b-404d-b9e7-d9ca0d2135b5)

BoltAI app:
![CleanShot 2024-07-10 at 21 55 06@2x](https://github.com/BoltAI/BoltAI/assets/187720/7bdf14a6-0d58-456d-b3ca-d860915ee409)

**Comment by longseespace** [comment]
There is another result and it might be what you were referring to (I guess). But it's NOT Dall E. It's Code Intepreter which is not available in BoltAI yet.

Please let me know if it was the case.

![CleanShot 2024-07-10 at 21 57 15@2x](https://github.com/BoltAI/BoltAI/assets/187720/647fba9f-ea91-41b4-9fb3-7b8862e31cd9)

**Comment by MichaelPietroforte** [comment]
How do you know it is Code Interpreter?

**Comment by longseespace** [comment]
![CleanShot 2024-07-10 at 22 05 22@2x](https://github.com/BoltAI/BoltAI/assets/187720/e5a7e3a8-748a-46f8-9de3-b4490c25ebd9)

![CleanShot 2024-07-10 at 22 06 08@2x](https://github.com/BoltAI/BoltAI/assets/187720/85b7c7a8-f3ab-4878-8e5d-2eacd7dde1e6)

**Comment by MichaelPietroforte** [comment]
You are right. My prompts are always in this category, and I assumed this was DALL-E 3.

Anyway, I apologize for my incorrect accusations. I love BoltAI! I doubt that Apple will be able to do this better in Sequoia.

**Comment by longseespace** [comment]
Hey, no worries. I need to add support for Code Interpreter. It causes the confusion for many people.
