### ISSUE TITLE
Extra padding below user message

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#13]
Not really a bug but wanted to get it out there.

In the recent update, some additional space was added after every user message. I realize it is there to act as placeholder space for the new context menu button and the "Show Full Message" button but it looks a bit off for messages when they have neither of these two elements. (when not hovered or when not long enough)

How about putting the context menu button to the left of user messages? Would also make it more consistent with it being on the right for assistant messages. And how about showing the  "Show Full Message" button optionally by only showing it for long messages that need it?

**Comment by longseespace** [comment]
Feel free to reopen if you sitll think this is needed.
