### ISSUE TITLE
Web Search plugin not working with OpenRouter API  and GPT4o/mini

### ISSUE THREAD

**Issue by mbac** [BoltAI/BoltAI#133]
Web search isn't working for me when using OpenRouter as a provider and GPT4o or GPT4 mini models.

App just displays JSON data of the request, but it doesn't actually perform the search:

 Claude 3.5 Sonnet works fine via Anthropic API; don't have OpenAI key to test with them.

Using version 1.6.11 on macOS 14.5, Setapp license…

<img width="926" alt="Screenshot 2024-07-27 at 23 37 43" src="https://github.com/user-attachments/assets/f1fbab59-d579-4d42-89d5-ecd5ede7f1e7">

**Comment by longseespace** [comment]
I've released v1.17.0 (standalone version) to address this. It will be available on Setapp soon.

**Comment by mbac** [comment]
With version 1.17.1 problem solved both with OpenRouter and OpenAI models. One last thing is that if you set OpenRouter to Auto (select model depending on prompt characteristics), the search plugin breaks. I do realize this isn't so much a bug report as it's a feature request, but…

Would it be ever possible to implement search so that if one select Auto (prompt decides) and search is required, OpenRouter switches to Function Calling-compatible models?

Thansk for this app anyways!

<img width="978" alt="Screenshot 2024-07-28 at 23 04 09" src="https://github.com/user-attachments/assets/456cf939-ce6b-415d-9120-95327bec8ee3">

**Comment by longseespace** [comment]
> Would it be ever possible to implement search so that if one select Auto (prompt decides) and search is required, OpenRouter switches to Function Calling-compatible models?

Unfortunately this is beyond our control. You can file a feature request on the OpenRouter Discord channel or their help email
