### ISSUE TITLE
Use `⌘ command` + `⌥ option` + `s` to toggle sidebar

### ISSUE THREAD

**Issue by kyranjamie** [BoltAI/BoltAI#134]
Mentioned this on Canny, but raising here because it's so deeply important to me (lol).

This shortcut a common standard for macOS apps, and one that is much more ergonomic than the existing `control + command + s`, because right hand does the modifiers, and left the s.

Precedent: Finder, Reminders, Notes.

As discussed on Canny, it could also be both shortcuts, as is the case with Finder.

**Comment by longseespace** [comment]
Alright. I'm going to add this lol

**Comment by longseespace** [comment]
I've fixed this in the latest verison: https://boltai.canny.io/changelog/v1180-build-94

**Comment by kyranjamie** [comment]
Legend Daniel 🙏🏼
