### ISSUE TITLE
[Feature Request] Temporary chat

### ISSUE THREAD

**Issue by ExAthy** [BoltAI/BoltAI#138]
Most of the time, I just want to ask the AI ​​some questions on a whim, and I don't want to train the AI. I can't clear the historical chat history. I can only delete it again and then add a new chat. This step is too cumbersome. If there is a temporary chat, I can get answers to my questions quickly.

**Comment by rb81** [comment]
**+1** on this one. It would be good to have throw-away conversations. A shortcut to open a chat window that doesn't end up in the history list would be good. I end up with tons of single question chats saved which I have to manually delete.

**Comment by longseespace** [comment]
Great idea. I will add this soon.

**Comment by longseespace** [comment]
I've added this in the latest verison: https://boltai.canny.io/changelog/v1180-build-94

**Comment by rb81** [comment]
This is an awesome addition, @longseespace! Thanks for making this happen!

An idea building on this: might be worth considering being able to set a specific model for the temp chats. Could be a setting under "Models", in the same way you set default for regular chats...
