### ISSUE TITLE
Temp Chat Showing Double Config Menu

### ISSUE THREAD

**Issue by rb81** [BoltAI/BoltAI#142]
**Describe the bug**
Temporary chat showing double config menus. Unclear if this has an intended purpose, so assuming it's a UI bug.

**To Reproduce**
Start temporary chat.

**Expected behavior**
One config menu for the chat.

**Screenshots**
<img width="396" alt="Screenshot 2024-08-11 at 5 46 07 PM" src="https://github.com/user-attachments/assets/b8dd6e46-105f-4ea0-9ded-d910c18f3933">

**Version (please complete the following information):**
 - macOS: 14.6
 - app version: v1.18

**Comment by lendle** [comment]
I see this in all chats in their own window, not just temp chats. 
<img width="493" alt="image" src="https://github.com/user-attachments/assets/3ad71cd6-c97d-4536-b1e6-e880283e2c54">

**Comment by longseespace** [comment]
This is fixed in `v1.18.1`
