### ISSUE TITLE
Can't use Ollama: llama3:latest does not support tools

### ISSUE THREAD

**Issue by DavidNix** [BoltAI/BoltAI#143]
**Describe the bug**

I can't use the Ollama models at all. I see this error on the first chat.

<img width="966" alt="Xnapper-2024-08-13-09 48 00" src="https://github.com/user-attachments/assets/e7430aae-7a34-444c-ade1-1a674e643ded">

**Version (please complete the following information):**
 - macOS: 14.5 (23F79)
 - app version v1.17.2

**Comment by longseespace** [comment]
Thanks. This error means that model doesn’t support function calling. Can you disable all plugins and try again?
