### ISSUE TITLE
Incomplete response in chat

### ISSUE THREAD

**Issue by lendle** [BoltAI/BoltAI#144]
**Describe the bug**
I just installed boltai and added a new anthropic api key. I'm using sonnet 3.5. In my first couple of chats, I got an incomplete response. For example, I say `Who are you` and I get a response like `I am BoltAI, an artificial intelligence created to be a helpful digital assistant. I don't have a physical form or` and it just stops.  Maybe it had something to do with the fresh install because it seems okay now. I will update with more information if it happens again. This happened for the first 2 or 3 chats but I don't have a screenshot. Regenerating the response a few times eventually got a complete response.

**To Reproduce**
I cannot reliably reproduce the issue, but this is what I did:
1. Install boltai via brew and open it
2. Create a new anthropic api key and configure boltai to use it, using sonnet 3.5 and setting that as the default model
3. Start a new chat and say something simple like "Hello"
4. The response cuts off after a dozen words or so.

**Expected behavior**
Response is complete.

**Screenshots**
None

**Version (please complete the following information):**
 - macOS: 14.3.1 (23D60)
 - app version: v1.18.0
 - [ ] Setapp Version?

**Additional context**
None

**Comment by lendle** [comment]
Are logs available anywhere? I can't find them, but happy to include if they exist somewhere.

**Comment by longseespace** [comment]
Thanks for the feedback. If I have to make a guess, their server has been overloaded the last few days. That's likely why.

I do not have the logging functionality in BoltAI. Partly because privacy and security needed to make it right.

You can use proxyman (https://proxyman.io) to track every request in and out of BoltAI. The free version is enough I think.

![CleanShot 2024-08-13 at 23 52 54@2x](https://github.com/user-attachments/assets/d7119c41-d7b1-4f0d-ac67-ba834ab7465c)

**Comment by lendle** [comment]
I do see some errors in the anthropic console model logs. I should have checked that first. 
```
{
  "client_error": false,
  "code": 529,
  "detail": "Overloaded"
}
```

There are only a couple of these and I _think_ I experienced the issue in the app more than that, but this seems like the most likely cause. I'll try out proxyman and reopen the issue if it comes back.

**Comment by longseespace** [comment]
Ah I see. I will find a way to improve the error message. It's a bit annoying since when this happens, they don't follow the standard error json format.
