### ISSUE TITLE
Model Support Issue (latest: ChatGPT-4o) - Tools is not supported in this model.

### ISSUE THREAD

**Issue by IGI2** [BoltAI/BoltAI#145]
I've encountered an issue with the Bolt app. The error message appears when trying to use a specific model:

<img width="679" alt="image" src="https://github.com/user-attachments/assets/f805364f-04d8-4acd-9b1e-1677b1968939">

I cannot use this model:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/453660f7-68ec-48dc-99c4-1b979526449c">

Error: "Tools is not supported in this model. For a list of supported models, refer to https://platform.openai.com/docs/guides/function-calling/supported-models."

PS: It might be beneficial to clean up the naming conventions to ensure parity with the OpenAI documentation for the API.

**Comment by IGI2** [comment]
Okay, I read what you wrote: "This error means that model doesn’t support function calling. Can you disable all plugins and try again?"

However, is this desired behavior? Other variants/versions of 4o, meaning 08-06, or 05-13, or just -4o, are okay with plugins enabled.

Moreover, ChatGPT-4o naming convention appears unusual and does not indicate the distinction from GPT-4o.

**Comment by longseespace** [comment]
This is not a bug. This is expected. I understand the confusion and I will find a better way to address this. But this confusion comes from OpenAI. They recently released 2 models:

- `gpt-4o-2024-08-06`: For API use, can use tools (BoltAI plugins)
- `chatgpt-4o-latest` (the one you're using): This model tracks the **chat** model used in the official ChatGPT app. It doesn't seem to support tool use.

References: 

- https://platform.openai.com/docs/models/gpt-4o
- https://x.com/OpenAIDevs/status/1823510395619000525

Feel free to reopen if you have other questions
