### ISSUE TITLE
[Bug] Dark mode: Invisible text in "Edit Message" window when editing prompts

### ISSUE THREAD

**Issue by suntereo** [BoltAI/BoltAI#146]
**Describe the bug**
When using dark mode and editing a previously used prompt, the background color of the right panel in the "Edit Message" window is not set correctly. The background remains white while the text is also white, making the text invisible.

**To Reproduce**
1. Enable dark mode on the system
2. Open the app
3. Select a previously used prompt to edit
4. Click on the edit option to open the "Edit Message" window
5. Observe the right panel of the window

**Expected behavior**
The right panel of the "Edit Message" window should have a dark background to match the dark mode theme, allowing the white text to be visible and readable.

**Screenshots**
This image shows the "Edit Message" window with a dark left panel and a white right panel. The text in the left panel is visible, but the right panel appears blank due to the white-on-white color scheme:
<img width="793" alt="image" src="https://github.com/user-attachments/assets/3488c04e-e80f-4561-b13e-9e3b54baeccb">

**Version (please complete the following information):**
 - macOS: Sonoma 14.5
 - app version: v1.18.2 (build 96)

**Comment by longseespace** [comment]
Thanks for the bug report. I'm working on the fix right now.

**Comment by longseespace** [comment]
This is fixed in v1.18.4.

**Comment by suntereo** [comment]
Wow, thank you for fixing this so quickly! Really appreciate it
