### ISSUE TITLE
Token error 8K Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by ThibautPV** [BoltAI/BoltAI#149]
Hello,

Following the latest update, it is no longer possible to use 8K tokens for output (maximum 4K authorized).
![Capture d’écran 2024-08-15 à 17 48 33](https://github.com/user-attachments/assets/875c02bb-cf36-41d3-9752-6d7cce960834)

Regards,

**Comment by longseespace** [comment]
I fixed this in v1.18.4. Update when you can.
