### ISSUE TITLE
The chat preference popup is very slow to show/hide

### ISSUE THREAD

**Issue by vimcaw** [BoltAI/BoltAI#15]
When I click on chat preferences, it takes a second or two for the popup layer to appear, and the same when I close it, it seems very laggy.

https://github.com/BoltAI/BoltAI/assets/21964227/48e334f2-440d-461a-a1f4-034af9637749

**Comment by longseespace** [comment]
I recently fixed a memory leak and this issue should be fixed. Do you still experience this @vimcaw? I'm closing it now. Feel free to reopen if it still happens

**Comment by vimcaw** [comment]
> I recently fixed a memory leak and this issue should be fixed. Do you still experience this @vimcaw? I'm closing it now. Feel free to reopen if it still happens

Yep it become much smoother now, thanks!

**Comment by DanBDoordash** [comment]
@longseespace I am still experiencing high memory usage. It's at 3.22GB of ram with only 6 chats in my sidebar (plus the 7 example chats).

I'm on v1.13.1

**Comment by longseespace** [comment]
@DanBDoordash Thanks. Can you share your mac's specs and how you usually use BoltAI? There might be another memory leak somewhere else that I'm not aware of.

Thanks

**Comment by DanBDoordash** [comment]
MBP on Apple M2 chips. 16 GB RAM, running Sonoma 14.3

When my chats get long (say, 2 dozen messages exchanged), the chat window gets very laggy and memory usage spikes (currently sitting at 2 GB)/

@longseespace happy to provide more info!

**Comment by longseespace** [comment]
If the chat is not sensitive, can you export and share it with me. My email: daniel@boltai.com

Thanks.

**Comment by DanBDoordash** [comment]
Sorry, unfortunately I can't. But, it happens for _any_ chat that exceeds some amount of messages.

**Comment by longseespace** [comment]
Gotcha. No worries, I figured out the issue. Will fix it soon.

**Comment by longseespace** [comment]
Hey @DanBDoordash. I think I've fixed this in the latest version (v1.13.6). I've reworked the message list implementation:

- It supports pagination now (scroll top to load more)
- It doesn't re-render on every keystroke (there was a bug)

Can you confirm?
