### ISSUE TITLE
[Feature Request] Persistent Preview Toggle State in Edit Message Screen

### ISSUE THREAD

**Issue by suntereo** [BoltAI/BoltAI#150]
I would like to request a new feature for the Edit Message screen. Currently, when a user hides the preview and then closes the window, the preview state is not remembered when the window is reopened. I'm referring to this feature here:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/d4c18ee7-591b-47f2-bfc7-dc25dfa5e5c4">

Feature request:
Remember the state of the preview toggle (shown/hidden) in the Edit Message screen
Maintain this state between sessions, even after closing and reopening the window
This enhancement would improve user experience by preserving user preferences and reducing the need for repeated actions.

**Comment by longseespace** [comment]
Ah right. Good idea!

**Comment by suntereo** [comment]
I see this has been added in build 99. Thank you!!
