### ISSUE TITLE
Can't use Ollama: llama3.1 :70b

### ISSUE THREAD

**Issue by Sentimelo** [BoltAI/BoltAI#152]
**Describe the bug**
Llama3.1 models cannot be used in Ollama

**To Reproduce**
1. Go to new chat
2. Click on Provider Ollama
3. Select Model LLama3.1:70b
4. Time response

**Expected behavior**
I can't work with LLama 3.1 models via Ollama at all. It spins the wheel and finally tells me that the time has elapsed.

**Version**
 - macOS: 14.6.1
 - app version 1.18.4 build 98

**Comment by longseespace** [comment]
Have you tried restarting Ollama. Usually this is a problem from Ollama and not BoltAI. I couldn’t reproduce on my end unfortunately.

**Comment by longseespace** [comment]
Hi @Sentimelo. Does it work for you now?

**Comment by Sentimelo** [comment]
Hi,

Yes, it works for me now.

Thank you for resolving the issue.

Best regards.





Martin Kováč

Rezervujte si meeting
E: ***@***.***
T: +421 949 55 66 75
