### ISSUE TITLE
Failed to save changes for Together.AI.

### ISSUE THREAD

**Issue by danny-su** [BoltAI/BoltAI#155]
<img width="580" alt="BoltAI 2024-09-02 09 36 53" src="https://github.com/user-attachments/assets/6d42429d-268a-4340-bec0-aa2a5972f4d0">

**Version (please complete the following information):**
 - macOS: 14.6.1
 - app version v1.19.1 (Setapp)
 - [x] Setapp Version?

**Additional context**

**Comment by longseespace** [comment]
Thanks. Working on it

**Comment by longseespace** [comment]
Fixed in v1.20.0
