### ISSUE TITLE
Prompt to generate image gives text output in BoltAI, but image in ChatGPT web interface

### ISSUE THREAD

**Issue by Robert-M-Muench** [BoltAI/BoltAI#157]
Prompt used:

---
Generate an engaging and grasping image for ABC and use only these colors:

#598F0F
#D13226
#DCDCD5
#A29876
#78B1C6
#111F2B

for the following text:

{input}

---

It works in ChatGPT (gives image) but not BoltAI (gives text).

**Comment by longseespace** [comment]
It's likely that you haven't enabled the Dall E plugin, or you don't use the Dall E model directly. Unlike ChatGPT app, BoltAI does not always include image generation by default to save token costs etc.

There are 2 ways you can generate images in BoltAI:

1. Use the text-to-image models directly. This allows you to directly interface with the Dall E model. Power users usually use this.
2. Use the dedicated plugin. This works similarly to the ChatGPT web app, where the GPT-4o model would generate the prompt for you, and then send to Dall E model.

You can learn more here: https://boltai.com/docs/chat-ui/image-generation

Can you try again with this.

**Comment by longseespace** [comment]
Any update @Robert-M-Muench?

**Comment by longseespace** [comment]
Feel free to reopen if it doesn't work
