### ISSUE TITLE
Bolt forgets default model after restart

### ISSUE THREAD

**Issue by swarmer** [BoltAI/BoltAI#158]
**Describe the bug**
Bolt forgets my default model (ollama) after every restart.

**To Reproduce**
1. Select an ollama model as the default
2. [not sure but maybe related?] Open a chat, change context from last 10 messages to All previous messages, save settings as default
3. Start new chats, they work as expected, in settings ollama is default.
4. Quit app
5. Launch app, and open a new chat
6. Claude Instant 1 is opened.
7. In settings, no default model is selected

**Expected behavior**
Nothing changes after app restart.

**Version (please complete the following information):**
 - macOS: 14.6.1
 - app version: 1.20.0

**Additional context**
There's all kinds of bugs or fixes after a restart, I can't write up them all, but you never know if something will break, or start working properly after you quit and reopen the app. One thing I remember is that the instant command settings, or maybe alternative instant command settings wouldn't apply until you restart the app.

**Comment by swarmer** [comment]
I remember sometimes the default model would be saved just recently, but now it's completely broken, I can't make it remember any default model after restart no matter what I do.

**Comment by longseespace** [comment]
Sorry. Found the issue. Will release a fix in the next 30 mins. I recently added support for iCloud Sync for some configurations and this seems to cause the issue.

**Comment by longseespace** [comment]
I pushed the fix in `v1.20.1`. Can you confirm?

**Comment by swarmer** [comment]
That was quick! Seems to good now, thank you so much!
