### ISSUE TITLE
Web Search (Beta)

### ISSUE THREAD

**Issue by keimaumau** [BoltAI/BoltAI#16]
I get the following error message when I enter my Search Engine ID & Search API Key:

_The operation couldn't be completed. (RealHTT.HTTPError error 1.)_

I get the same error if I type in a bunch of jibberish too...

**Comment by longseespace** [comment]
Thanks. I will fix the error message today. It's not very user friendly at the moment. Sorry 😅

**Comment by longseespace** [comment]
This has been fixed in v1.15.9. Can you confirm? Thanks
