### ISSUE TITLE
"Default Model" Not Sticky

### ISSUE THREAD

**Issue by armen-y** [BoltAI/BoltAI#164]
**Describe the bug**
The settings allow one to select a default model, but the selection is not sticky.

**To Reproduce**
1. Go to 'BoltAI -> Settings....'
2. Click on 'Models -> OpenAI'
3. Click on the 'Default Model' dropdown and select 'GPT-4o'
4. Close the window.
5. Go to 'BoltAI -> Settings....'
6. Click on 'Models -> OpenAI'
7. Observe the default model.

**Expected behavior**
The default model is the same model that was previously selected by the user.

**Observed behavior**
The default model is 'GPT4o-mini'

**Screenshots**
![Default Model Not Sticky](https://github.com/user-attachments/assets/6c97cf17-632c-46d1-a65d-87091b7fbbc6)

**Version (please complete the following information):**
macOS: 14.6.1
app version v1.20.1 (build 102)

**Additional context**
The model that is selected for new chats does not match the user selection in step 3.

**Comment by longseespace** [comment]
This has been fixed in the latest version. Please update.

**Comment by longseespace** [comment]
Feel free to reopen if it doesn't work

**Comment by armen-y** [comment]
Works! Thanks for fixing this, Daniel.
