### ISSUE TITLE
Error related to non-whitespace text with Claude

### ISSUE THREAD

**Issue by jlpajares** [BoltAI/BoltAI#165]
**Describe the bug**
Since a couple of weeks (aprox) if I try to use Clause Sonnet 3.5 in a chat or a command I get this error: 
> responseUnsuccessful(description: "status code 400system: text content blocks must contain non-whitespace text")

**To Reproduce**
Just start a chat or invoke a command using Claude

**Expected behavior**
Work as usual 😉

**Version (please complete the following information):**
 - macOS: 14.6.1
 - app version v1.20.5
 - [X] Setapp Version?

**Comment by longseespace** [comment]
Ah sorry. Working on the fix right now. A workaround for this is to put something in the System Prompt, any text as long as it's not whitespace.

**Comment by jlpajares** [comment]
Thanks for the tip!
