### ISSUE TITLE
Bug: After latest update, app hangs indefinitely during follow-up prompts

### ISSUE THREAD

**Issue by suntereo** [BoltAI/BoltAI#168]
**Describe the bug**  
The BoltAI application hangs indefinitely when processing follow-up prompts, requiring the app to be force quit.

**Additional context**  
I just updated to the latest version today and have been experiencing this issue consistently with follow-up prompts. It happens most of the time, requiring me to kill the app each time it hangs.

**To Reproduce**  
1. Open BoltAI on macOS.
2. Enter an initial prompt and submit it.
3. After receiving a response, enter a follow-up prompt.
4. The app hangs, displaying the Mac circle of death, and does not respond.

**Expected behavior**  
I expected the app to process the follow-up prompt in a timely manner and provide a response without hanging.

**Screenshots**  
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/ae95f198-9192-462c-a805-b957bea057a3">

**Version:**  
 - macOS: Sequoia 15.0  
 - app version: 1.21.0 (build 107)

**Comment by suntereo** [comment]
This might have nothing to do with follow-up prompts. I just got it again, but this time it happened when I deleted a prompt from the list on the top left.

**Comment by longseespace** [comment]
I've released v1.21.1 to fix this. Can you confirm? The issue was that I upgraded macOS & Xcode, and well, Xcode being Xcode 😅

**Comment by suntereo** [comment]
It seems to be fixed now on my end. Thank you so much!
