### ISSUE TITLE
Weird lines on chat page on  v1.12

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#17]
I am seeing some weird lines below the end of chat with the latest update. It is also there on an empty chat session page:

![Screenshot 2023-12-07 at 7 08 08 PM](https://github.com/BoltAI/BoltAI/assets/77480421/edc867e3-e5cb-466b-9770-1da423635fc7)

<img width="958" alt="image" src="https://github.com/BoltAI/BoltAI/assets/77480421/8ad6e888-20b7-4dc5-9109-e2538ae523eb">

**Comment by longseespace** [comment]
I've fixed this in v1.12.1
