### ISSUE TITLE
Can't Rename Archived Chats

### ISSUE THREAD

**Issue by armen-y** [BoltAI/BoltAI#171]
**Describe the bug**
Can't rename archived chats. When right-clicking on the chat and selecting "Rename Chat...", no popup appears to allow the user to do so.

**To Reproduce**
1. Go to 'Archived Chats view'
2. Rt-click on any pre-existing chat's title in the sidebar.
3. Click on "Rename Chat..."

**Expected behavior**
A popup appears, allowing the user to enter the new chat title.

**Observed behavior**
Nothing seems to happen from the user's perspective. 

**Screenshots**
![Rename Archived Chats](https://github.com/user-attachments/assets/ef777c69-d93f-411b-9950-047a8896eb9f)

**Version (please complete the following information):**
 - macOS: 14.7 (23H124)
 - app version v1.21.1 (build 108)

**Comment by longseespace** [comment]
Fixed in v1.22.0: https://boltai.com/changelog

**Comment by armen-y** [comment]
Thank you, Daniel. -A.On Sep 27, 2024, at 6:13 AM, Daniel Nguyen ***@***.***> wrote:﻿
Fixed in v1.22.0: https://boltai.com/changelog
