### ISSUE TITLE
OpenAI's o1 series models from GitHub cannot be added to BoltAI due to the stream parameter.

### ISSUE THREAD

**Issue by danny-su** [BoltAI/BoltAI#172]
**Describe the bug**
OpenAI's o1 series models from GitHub cannot be added to BoltAI due to the stream parameter. If the stream option is unchecked, it should be ignored instead of assigning a false value.

**Screenshots**
![70131](https://github.com/user-attachments/assets/27010913-d731-4c64-90b9-185b7a963874)
![74218](https://github.com/user-attachments/assets/d50e75d4-b4b6-4ce0-87f2-88ebcc13d8da)

**Version (please complete the following information):**
 - macOS: 15.0
 - app version v1.21.1
 - [x] Setapp Version?

**Additional context**

**Comment by longseespace** [comment]
Ah good eyes. Will fix. This is Azure, not Github, right?

**Comment by danny-su** [comment]
@longseespace  These models are published on the GitHub marketplace. Here is the link: https://github.com/marketplace/models/, but they are deployed on Azure.

**Comment by longseespace** [comment]
Fixed in v1.22.0: https://boltai.com/changelog
