### ISSUE TITLE
Command-Shift-Return to submit prompt breaks other apps (Obsidian)

### ISSUE THREAD

**Issue by brandonzylstra** [BoltAI/BoltAI#175]
**Describe the bug**

I have suffered from this for a LONG TIME, because it was not only not obvious that something outside of Obsidian was causing the problem, nor which thing that was, nor how to fix it.  I finally found buried deep in Advanced → Inline Trigger Phrases → Trigger Methods the setting that was causing the problem.  When BoltAI uses Command-Shift-Return in that location then I can't use Command-Shift-Return in Obsidian, which breaks my second most common use case for Obsidian: creating task entries and marking them done.

I don't see any reason that the keystroke to send prompts should be global, and affect other apps.  If there is a good reason, please explain it to me here, and please make it clear in the UI that this is a global keystroke. 

**To Reproduce**

1. Open your Bolt AI preferences
2. Go to Advanced → Inline Trigger Phrases → Trigger Methods
3. Click on the Trigger Method select list
4. Select Command-Shift-Return
5. Open Obsidian
6. Ensure that Obsidian is configured to use Command-Shift-Return to create and complete tasks.
7. Try creating and completing a task
8. Notice that it doesn't work.

**Expected behavior**

I expect this keystroke to not affect anything outside of Bolt AI.

**Version (please complete the following information):**
 - macOS: 14.7 (23H124)
 - app version 1.21.1
 - [x] Setapp Version Version 3.40.0b

**Comment by longseespace** [comment]
Hi Brandon. You can set the trigger method to something else. 

It **has** to be global because otherwise BoltAI would not work. Don’t forget you’re currently working with a different app (Obsidian in this case). Local keyboard shortcut only works when BoltAI is the active application.

**Comment by longseespace** [comment]
I'm closing this as it's not really a bug. There is indeed an UX issue and I've stopped setting the default Keyboard Shortcut for a new user. Feel free to reopen the issue if you have other questions or suggestions. Thx

**Comment by brandonzylstra** [comment]
If that's supposed to be global then the UI should clearly state that fact.  That seems like a bug to me.
