### ISSUE TITLE
PDF Pals?

### ISSUE THREAD

**Issue by hhannis** [BoltAI/BoltAI#176]
**Describe the bug**
In openrouter, requests from bolt is identified as PDF Pals

**To Reproduce**
1. Use openrouter in "models" settings
2. Do a request
3. Check the logs - https://openrouter.ai/activity

**Expected behavior**
request should be identified as coming from Bolt.AI

**Screenshots**

**Version (please complete the following information):**
 - macOS: [15.0 (24A335)]
 - app version [v1.21.1 (build 108))]

**Comment by longseespace** [comment]
Ohhh my bad. Must be a copy & paste mistake. Working on this now
