### ISSUE TITLE
App freezes on every new message

### ISSUE THREAD

**Issue by yunapotamus** [BoltAI/BoltAI#177]
**Describe the bug**
See title

**To Reproduce**
1. Create a new chat
2. Type a message and press enter. (I was using Claude Anthropic 3.5 Sonnet.)
3. Repeat step 2 until freeze occurs. Always happens within 1-2 tries.

**Expected behavior**
App should not freeze

**Screenshots**
n/a

**Version (please complete the following information):**
 - macOS: 15.0
 - app version 1.21.0
 - [ ] Setapp Version?

**Additional context**

**Comment by yunapotamus** [comment]
This is the error report.

[spin.txt](https://github.com/user-attachments/files/17172164/spin.txt)

**Comment by longseespace** [comment]
Thanks. Can you try the new version `v1.22.0`. I improved the compatibility with macOS Sequoia in this version

**Comment by longseespace** [comment]
Any update @yunapotamus? Does it work?

**Comment by choval** [comment]
Hi, Mac os sequoia here. Bolt 1.22.0 build 109. All ai messages are blank, it hangs immediatly.

**Comment by yunapotamus** [comment]
1.22 seems to fix my issue, thanks. Did not run into the other reported issue.

**Comment by longseespace** [comment]
> Hi, Mac os sequoia here. Bolt 1.22.0 build 109. All ai messages are blank, it hangs immediatly.

Do you still have this issue @choval? It seems to be fixed for yuna
