### ISSUE TITLE
Better validation when editing or regenerating messages out of context

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#18]
Thanks for the clear context feature.

I noticed an issue where if a user tries to edit a message above the reset marker, it would delete all messages below it (as expected) but the request would not go through and give an error message like "The message cannot be empty".
The reset marker disappears in this case but the out-of-context messages included the newly edited one and the messages above are greyed out (as expected). New messages sent form input box seem to **not** be greyed out but I am not sure if the expected context length is being sent in this case.

I can understand why this is happening but was wondering what could be a good way to deal with this. 
The simplest approach could be to simply disable regenerating/editing from messages that are above the reset marker. Rest options could stay.
Alternately, the reset marker could be shifted up to right above the message thats being edited or regenerated. But there may be several edge cases to consider if going this route.

**Comment by longseespace** [comment]
I think this has been fixed. Feel free to reopen otherwise.
