### ISSUE TITLE
Can't add new Azure OpenAI model

### ISSUE THREAD

**Issue by Romportl** [BoltAI/BoltAI#180]
When I add new Azure OpenAI model in Settings, it cannot be saved. I add URL, key and the name of the model, click on Save, nothing happens. When I leave the form for this model and return back, all the fields are empty. It also cannot be renamed to anything else than default "Azure".

BoltAI version: 1.22.1

**Comment by Romportl** [comment]
![Snímek obrazovky 2024-10-02 v 20 14 17](https://github.com/user-attachments/assets/7de9d313-503c-4948-b277-0d888acc1c14)

It's this form. Nothing I write here can be Saved. It always gets back to this empty form.

**Comment by longseespace** [comment]
Hi @Romportl, can you share the endpoint url with me (via email, mine: daniel@boltai.com). I don't need the api key.

There seems to be an issue with Azure's new URL format.

Thanks

**Comment by Romportl** [comment]
done
