### ISSUE TITLE
Input cannot be edited / Truncation of long Text in the Input Fields 

### ISSUE THREAD

**Issue by latent-capital** [BoltAI/BoltAI#185]
**Describe the bug**
Bolt truncates the displayed portion of the text in the chat input field

**To Reproduce**
1. Go to 'input field of a chat
<img width="806" alt="Screenshot 2024-10-08 at 20 11 57" src="https://github.com/user-attachments/assets/deb61c03-7acf-4c18-a2f2-9f1faf93870e">'
2. Paste a long text into the input field, 1000 words should be enough
3. The display portion of the text in the input field is being truncated, you can no access the whole input 
The entire text can still be selected with CMD+A, but the scroll bars do not reflect this.
4. There is a related bug (likely once born as a feature) - when you select another chat session before sending the long text, and then cycle back,  the input field with long text is reduced to two lines (until new input is entered).
<img width="919" alt="Screenshot 2024-10-08 at 20 18 54" src="https://github.com/user-attachments/assets/075d2b70-f7aa-4b58-bdf9-12480acce0ab"> the screenshot shows all that's left of 2500 lines source code in this situation (again the text is still "there" and can be sent or retrieved with CMD+A, but it is hidden from the user in the most distracting way possible:  when deleting the two lines, the input field appears empty. when switching to another chat and back and forth, some parts re-appear.

**Expected behaviors**
- when pasting long text into the input field, the API client must display the entire text in a cultivated way for reviewing and editing - just like you could paste a 10000 word text into this form on GitHub.
- when switching chats back and forth before sending the input, either discard the input, or re-open the initial chat in an identical state (without re-sizing the input field or even further truncating the text)

side-note:
a sophisticated GUI could even augment the input in the following ways:
- line numbers
- token count
- syntax highlightning
- tokenization ()

**Version:**
 - macOS: 15
 - app version 1.22.2

**Additional context**
- Just switched from MIndMac for similar annoyances - and now again left with a dysfunctional GUI client.
- Developers of API clients seem to neglect that input lengths of 1.000.000 tokens are now legitimate use-cases 
- To insert instructions for the LLMs, it is essential to review and edit such long inputs in the API client after pasting.
- In the presents state BoltAI lacks this basic functionality 

- The truncation (i.e. the present bug) disappeared temporarily while toggling certain settings that are not reproducible.
In any case here is the involved configuration.
<img width="442" alt="Screenshot 2024-10-08 at 21 33 02" src="https://github.com/user-attachments/assets/873e8795-5f48-433b-92d3-27d1f83838c3">

**Comment by longseespace** [comment]
Thanks for the bug report. To be clear, this is a rendering bug, not a data bug. The full prompt is still there. This has been on my todo list but I think the better solution is a dedicated, full-size editor like when you edit a chat message. 

Editing within that narrow input is generally not a good UX anyway.

**Comment by longseespace** [comment]
Fixed in `v1.23.0`: https://boltai.canny.io/changelog/v1230-build-112. Feel free to reopen the ticket if it doesn't work for you.
