### ISSUE TITLE
Assistant no longer working

### ISSUE THREAD

**Issue by kenbanks-peng** [BoltAI/BoltAI#188]
**Describe the bug**
Although it certainly worked previously, now the text of my chosen assistant does not get sent to my AI provider (openAI) when I start a new chat. 

**To Reproduce**
1. Preconfigure a default assistant: software developer
1. Start a new chat, observe assistant is software developer
2. Ask gpt what were the first instructions I provided.

**Expected behavior**
Previously it would respond according to the configured assistant text. 
Now it just says, you haven't provided any instructions. And follow-on responses do not conform to my assistant's instructions.

**Version (please complete the following information):**
 - macOS: 15.0.1 (same on 14)
 - app version: v1.24.0

**Comment by longseespace** [comment]
Which model did you use? I can't seem to reproduce the issue.

https://share.cleanshot.com/ffXCDw9J

**Comment by kenbanks-peng** [comment]
Model: GPT4-o

I restarted app several times (Quit app not just close) and it continued to fail. I then was playing around in the settings and without changing any settings to new values, restarted the app again and now the assistant works as expected. 

This has happened a few times before seemingly out of the blue and then it latches in the failed state for a while, even through cycling the app. Then I fix it without knowing how I fixed it. Sadly I am unable to have a more reliable reproduce.

My suspicion is that it might be associated with me upgrading to the latest release via homebrew on M2 'brew upgrade'. I likely upgraded BoltAI without closing the prev BoltAI. But I would have thought quitting the app would resolve it right away in that case.

**Comment by longseespace** [comment]
Ah I see. There might be a problem when we open 2 instances of BoltAI at the same time. As the app synchronizes your setting to iCloud, it might result in a "sync loop".

I will fix it soon.

**Comment by kenbanks-peng** [comment]
Not your typical bug for sure. A bit obscure but your description certainly aligns with my upgrade flow. Nice job.

**Comment by kenbanks-peng** [comment]
Have gone through several upgrades without seeing this issue. Closing.
