### ISSUE TITLE
Chat jump to top of the messages.

### ISSUE THREAD

**Issue by NuazSafie** [BoltAI/BoltAI#19]
In the in-app chat window, sometimes during a long conversation, the chat view will jump back to the top or the first message after finishing a response.

https://github.com/BoltAI/BoltAI/assets/132314452/1f3218ea-b999-4f60-93da-1c1187eb746c

**Comment by longseespace** [comment]
Sorry for the issue. I'm working on the fix right now.

**Comment by longseespace** [comment]
I've been trying to replicate this issue all day today and wasn't able to, not a single one. I've tested on both Ventura and Sonoma. Any idea how to replicate it @vimcaw @NuazSafie @SilverMarcs :(

**Comment by NuazSafie** [comment]
@longseespace I've experimented with different settings in the General tab and even switched to GPT4, but unfortunately, it didn't solve the problem. The chat still keeps jumping to the top, and it seems like this issue occurs in every conversation. Right now, I've disabled the "Automatically scroll to bottom" option. 🥲

I'm considering reinstalling the app, but I'm worried that I might lose all my settings. Is there a way to back up the settings to avoid losing them?

**Comment by longseespace** [comment]
> @longseespace I've experimented with different settings in the General tab and even switched to GPT4, but unfortunately, it didn't solve the problem. The chat still keeps jumping to the top, and it seems like this issue occurs in every conversation. Right now, I've disabled the "Automatically scroll to bottom" option. 🥲
> 
> I'm considering reinstalling the app, but I'm worried that I might lose all my settings. Is there a way to back up the settings to avoid losing them?

Give me 30 mins. I will send you the beta version I’m trying to fix this. I don’t think reinstalling would help so maybe just wait a bit. Just to confirm, you’re on Sonoma right?

**Comment by vimcaw** [comment]
> I've been trying to replicate this issue all day today and wasn't able to, not a single one. I've tested on both Ventura and Sonoma. Any idea how to replicate it @vimcaw @NuazSafie @SilverMarcs :(

Just make chat history as long as possile, in my case (with very long history), it happen eachtime.

**Comment by vimcaw** [comment]
> > I've been trying to replicate this issue all day today and wasn't able to, not a single one. I've tested on both Ventura and Sonoma. Any idea how to replicate it @vimcaw @NuazSafie @SilverMarcs :(
> 
> Just make chat history as long as possile, in my case (with very long history), it happen eachtime.

Oh, it doesn't seem to have anything to do with length of chat history, I create a new conversation with only short history and it still comes up.

**Comment by vimcaw** [comment]
Also to add, it doesn't necessarily jump to the top, in the case of shorter chats, it often jumps to the neighborhood of the questions asked, like this: 

https://github.com/BoltAI/BoltAI/assets/21964227/a1fa5fb1-fa09-4075-ae23-97e6b151b8e9

**Comment by NuazSafie** [comment]
> you’re on Sonoma right?

Yup, im on Sonoma, thanks

**Comment by longseespace** [comment]
Can you guys give this beta a try. I don't have high hope that it would fix the issue but at least I could isolate it better. If it asks for Keychain Access, choose "Allow" or "Always Allow". Thanks

cc @NuazSafie @vimcaw 

https://download.boltai.com/beta/BoltAI-1.12.2-beta1.zip

**Comment by vimcaw** [comment]
> Can you guys give this beta a try. I don't have high hope that it would fix the issue but at least I could isolate it better. If it asks for Keychain Access, choose "Allow" or "Always Allow". Thanks
> 
> cc @NuazSafie @vimcaw
> 
> [download.boltai.com/beta/BoltAI-1.12.2-beta1.zip](https://download.boltai.com/beta/BoltAI-1.12.2-beta1.zip)

After much trial, the behavior of this new version in my case is that it jumps to the top and then right back to the bottom (which is the correct position) after the AI has replied.


https://github.com/BoltAI/BoltAI/assets/21964227/93e0555a-fc52-4c17-a7b6-dcc224d3ee0a

**Comment by vimcaw** [comment]
Also, after much trial, I found a pattern, the distance of the mistaken scrolling seems to be related to the length of the AI's answer, if the AI's answer is very short, it will only mistakenly scroll a short distance, and only if the AI's answer is very long will it scroll to the top.

https://github.com/BoltAI/BoltAI/assets/21964227/eb77256b-fb6f-4e8b-854d-ebebe7a2f38b

**Comment by vimcaw** [comment]
> Also, after much trial, I found a pattern, the distance of the mistaken scrolling seems to be related to the length of the AI's answer, if the AI's answer is very short, it will only mistakenly scroll a short distance, and only if the AI's answer is very long will it scroll to the top.
> 
>  CleanShot.2023-12-16.at.23.18.50.mp4

Oh, after a few tests, it doesn't look like that, the same content (short answers) still may scroll to the top and no pattern can be found.


https://github.com/BoltAI/BoltAI/assets/21964227/992256bb-5e84-4c76-a3a6-7c6d454705be

**Comment by NuazSafie** [comment]
> Can you guys give this beta a try.

I had the same result as @vimcaw. After responding, the chat suddenly jumps to the top and then quickly goes back down to the bottom.

**Comment by longseespace** [comment]
I think I've fixed it with this release. Can you give it another try @vimcaw @NuazSafie 

https://download.boltai.com/BoltAI-1.12.2-beta2.zip

It's no longer jumping around after the AI is finished.

**Comment by vimcaw** [comment]
> I think I've fixed it with this release. Can you give it another try @vimcaw @NuazSafie
> 
> [download.boltai.com/beta/BoltAI-1.12.2-beta2.zip](https://download.boltai.com/beta/BoltAI-1.12.2-beta2.zip)
> 
> It's no longer jumping around after the AI is finished.

Yup, after a few tests, I can confirm that it has been fixed, thanks!

**Comment by vimcaw** [comment]
> Happy to hear that @vimcaw. Did you run into any other issues? I changed the behavior of the real-time message completely.

No, I've tried code, Markdown content, etc., as well as different lengths of responses, and haven't encountered any problems.

**Comment by NuazSafie** [comment]
> I think I've fixed it with this release. Can you give it another try @vimcaw @NuazSafie

It appears that the issue has been resolved. Thank you very much for your help!

**Comment by longseespace** [comment]
Hey @NuazSafie, I've released the stable version `1.12.2` with this fix and a few more features. You should use it instead of the beta version. I'm not sure if you get the update notification with the beta version, probably not :D

https://boltai.com/changelogs/v1.12.2

**Comment by vimcaw** [comment]
> Hey @NuazSafie, I've released the stable version `1.12.2` with this fix and a few more features. You should use it instead of the beta version. I'm not sure if you get the update notification with the beta version, probably not :D
> 
> [boltai.com/changelogs/v1.12.2](https://boltai.com/changelogs/v1.12.2)

Not even when I check update manually, so I redownloaded and then replaced it.

**Comment by NuazSafie** [comment]
> Hey @NuazSafie, I've released the stable version `1.12.2` with this fix and a few more features. You should use it instead of the beta version. I'm not sure if you get the update notification with the beta version, probably not :D
> 
> https://boltai.com/changelogs/v1.12.2

Hey @longseespace  I've just installed the latest stable version and I must say, it's looking really great! The inline popup window is definitely working much faster now. I just wanted to say a huge thanks for taking my feature request into consideration and delivering this awesome update so quickly! Oh, and I also really appreciate the mention thank you! 🙏

**Comment by longseespace** [comment]
Thank you. Please keep the feedback coming. I use BoltAI everyday and since I understand every corner of it, there will be a lot blind spots that I'm not aware of 😅

**Comment by dsully** [comment]
I'm still seeing this behavior. If I switch chats, the scroll position jumps back to the top, which is really annoying. :(

**Comment by longseespace** [comment]
It’s a different issue I think. The original bug happened within a same chat. 

Are you on macOS 12 or 13+? @dsully

**Comment by dsully** [comment]
Sonoma 14.4.1 (23E224)

I can create a new issue if that's helpful.
