### ISSUE TITLE
Web Browsing Error

### ISSUE THREAD

**Issue by Lemon-Tech365** [BoltAI/BoltAI#192]
Sorry, OpenAl has rejected your request. Here is the error message: Invalid parameter: messages with
role 'tool' must be a response to a preceeding message with 'tool_calls'.

I get this error message when I try to use the web search/browsing feature.

<img width="359" alt="SCR-20241024-jvcu-2" src="https://github.com/user-attachments/assets/465782cb-ce0a-4f9c-821e-7df6a50a11b0">

Plugins I use:

<img width="289" alt="image" src="https://github.com/user-attachments/assets/58b027ca-f936-4520-bdc3-4e1f755c98bd">
<img width="286" alt="image" src="https://github.com/user-attachments/assets/15702a3b-d28a-484b-ae3a-48c9dffd002f">
<img width="290" alt="image" src="https://github.com/user-attachments/assets/9270ecda-e1b8-4129-bdc0-248757120540">

**Comment by Lemon-Tech365** [comment]
Web browsing seems to work on Claude 3.5 Sonnet Previous, so it's probably something that they updated with the api input parameters that's causing this.

**Comment by longseespace** [comment]
Hi. Which AI service/model are you using? In the screenshot I see GPT-4o, while you mentioned Claude 3.5 Sonnet. I'm a bit confused.

**Comment by Lemon-Tech365** [comment]
Hi, yes, so the error occurs on all models except the previous version on Claude 3.5. In other words, the web browsing only works on Claude 3.5 (previous). I can't seem to get it to work on any other models.

Thank you for your time and consideration.

**Comment by Lemon-Tech365** [comment]
I don't know if you resolved it, but it doesn't happen for me anymore. Thank you!
