### ISSUE TITLE
BoltAI not respecting port of "OpenAl-compatible Server (beta)" configuration 

### ISSUE THREAD

**Issue by maxaudet** [BoltAI/BoltAI#194]
**Describe the bug**
The specified port is not being used when attempting to reach the API for an" OpenAI-compatible" configuration.

**To Reproduce**
1. Create a new "OpenAl-compatible Server"
2. Configure it to use either LiteLLM or Ollama for example
3. Specify a port !=80 in the API endpoint
4. Click "Verify and Save", it will produce an error

**Expected behavior**
BoltAI should use the specified port when reaching the API.

**Screenshots**
BoltAI config:
![bolt_error](https://github.com/user-attachments/assets/0bdfa8de-3661-4f43-8d54-2fe5d682bc9d)

[ProxyMan](https://proxyman.io) showing the same behaviour:
![proxyman_bolt](https://github.com/user-attachments/assets/e9305b55-2c22-48aa-ba23-7c32475ec2a8)

Compared to the same call in Postman, which correctly uses the specified port:
![proxyman_postman](https://github.com/user-attachments/assets/5bb5dbeb-1478-4ebd-8a91-55ccb674eab4)

**Version (please complete the following information):**
 - macOS: Tested on both Sonoma 14.7 and Sequoia 15 and 15.1
 - app version v1.23.0 (build 112)
 - [x] Setapp Version?

**Additional context**
This seems new as it used to work, but I don't know in which version it changed.

**Comment by longseespace** [comment]
Thanks. I will fix this soon.

**Comment by longseespace** [comment]
This has been fixed in `v1.26.1`. It's will be live on Setapp soon (waiting for approval)
