### ISSUE TITLE
Feature Request: Google Gemini `codeExecution`

### ISSUE THREAD

**Issue by twilsonco** [BoltAI/BoltAI#196]
## **Describe the solution you'd like**
Google provides a `tool` called `codeExecution` via API that allows Gemini to generate and run programs before returning a response. https://ai.google.dev/gemini-api/docs/code-execution. 

This feature is really cool, because Gemini generates the code and runs it on Google's servers, using the code and its output to form its eventual response (which will also include the code and output for completeness). It therefore doesn't require any running of code on the user's machine; only a small change to the construction of the API request and the processing of the output.

- For typical responses, there's only a single `part` of type `text` that contains the model output. 
- When `codeExecution` is used, *and when the model has decided to use it* (which it determines based on the prompt context), the response will contain multiple `part`s, usually two of type `text` and one of type `executableCode`. The multiple `part`s can be combined into a nice coherent single output with text before and after the code. Here's how such an output might look (generated by an iOS/macOS Shortcut I made called "[Gemini via API](https://routinehub.co/shortcut/17624/)" that supports `codeExecution`)

![CleanShot 2024-10-28 at 09 38 53](https://github.com/user-attachments/assets/d91b58a1-41b8-46b4-b1ea-52ebfb4eb3a0)

## **Describe alternatives you've considered**
Existing plug-ins mentioned below are alternatives to this feature.

## **Additional context**

This has overlap with existing plug-ins (JavaScript Interpreter, AppleScript, and Shell Access) that could also be used to have a model generate code, which is then run on the user's machine. These plug-ins make the assumption that the model used is familiar with the respective programming language, which is probably a good assumption for JavaScript, but less so with AppleScript. 

With the Shell Access plug-in, you'd need to write a clear enough prompt that the model knows it needs to write the program itself in the desired programming language, then also write and run the commands to save it to a file, execute the code, fetch the output, and cleanup up any intermediate files. Those extra steps will likely degrade the quality of the overall output.

By contrast, this keeps the code execution server-side, which is more secure, and it's integrated into the Gemini response in a way that's been curated by Google, rather than a BoltAI prompting "trick" combined with on-machine running of code. This creates a reasonable expectation of higher output quality, since it's a process specifically designed for using the generated and executed code as additional context for the eventual model response.

**Comment by twilsonco** [comment]
I forgot to include that you don't want to enable `codeExecution` permanently, since it changes the Gemini system prompt when additional `tool`s are specified, and can degrade output quality for conversations where the tools aren't used or necessary. 

So this should be something that can be toggled by the user. I suppose the place to do that is in the General or Advanced sidebar within the conversation. Additionally, there could be a default setting specified in model settings.

![CleanShot 2024-10-28 at 10 03 33](https://github.com/user-attachments/assets/bf63cbd8-b8c8-4bde-8adb-97bdf5ec0cf7)

**Comment by longseespace** [comment]
Hey @twilsonco. BoltAI has already supported Code Execution. It's in the Plugins tab and is only available for Gemini models (screenshot below)

Documentation: https://boltai.com/docs/plugins/gemini-code-execution

Feel free to reopen if ot doesn't work.


![CleanShot 2024-10-28 at 23 49 31@2x](https://github.com/user-attachments/assets/d9eeb840-7093-4baf-a454-cf0b7129cfa5)

**Comment by twilsonco** [comment]
Ah! I checked plug-ins in settings but didn't check the full list of plug-ins when in conversation, so I missed it. 

Great work! Very slick implementation!

![CleanShot 2024-10-28 at 11 44 07](https://github.com/user-attachments/assets/22236789-b16e-4d55-b98a-522841c33d51)
