### ISSUE TITLE
The app icon is a folder

### ISSUE THREAD

**Issue by jlpajares** [BoltAI/BoltAI#197]
Since the previous update the icon of the app is a folder. I thought the next update 1.25.2 would solve it but the folder icon remained. I didn't touched the app, nor move it from the Setapp folder or edit it in any way. I have solved it by selecting the default icon in settings, instead of the Gandalf the White, which by the way seem to be now the same icon. Maybe the default icon has changed to Gandalf the White and that provoked the error?

Mac OS 15.0.1, Setapp version.

App icon: ![CleanShot 2024-10-29 at 10 52 49@2x](https://github.com/user-attachments/assets/2cc4e047-6df3-4e02-9327-4096234aeb2f)

Selected icon in settings: ![CleanShot 2024-10-29 at 10 55 48@2x](https://github.com/user-attachments/assets/ebcac454-b4b2-4607-a2c5-d10331c62d2e)

**Comment by longseespace** [comment]
Thanks. This keeps happening and I haven't found the root cause yet. I think it might be an issue with caching from Setapp. I has the exact same issue with Paw (RapidAPI) on Setapp.

**Comment by twardoch** [comment]
I have the same thing

**Comment by longseespace** [comment]
I will keep investigating but apparently this is a known issue for Setapp. 

https://www.reddit.com/r/Setapp/s/2cTxdTZ75W

**Comment by longseespace** [comment]
I think this has been fixed. Feel free to reopen.
