### ISSUE TITLE
Get error when I add the Perplexity AI API key.

### ISSUE THREAD

**Issue by IvanZugec** [BoltAI/BoltAI#199]
**Describe the bug**
When I enter in the Perplexity AI API key, I get an error.

**To Reproduce**
1. Settings
2. Plugins
3. Perplexity search
4. click on "save changes"

**Expected behavior**
It should save without error.

**Screenshots**
<img width="800" alt="2024-10-30_08-48-34" src="https://github.com/user-attachments/assets/be78f9e2-bd6b-4e18-84fa-f1cca0110f82">

**Version (please complete the following information):**
 - macOS: 14.7
 - app version 1.25.2

**Comment by longseespace** [comment]
Hey. Please update to `v1.25.4`

**Comment by longseespace** [comment]
It should look something like this:

![CleanShot 2024-10-30 at 15 03 41@2x](https://github.com/user-attachments/assets/9616a1fe-db93-4699-a7d7-bb34264bbaa4)

**Comment by IvanZugec** [comment]
That worked.

Thanks.
