### ISSUE TITLE
UI artifact in the chat window

### ISSUE THREAD

**Issue by badrbouslikhin** [BoltAI/BoltAI#2]
Hello,

I am currently encountering user interface (UI) anomalies within the chat window. More specifically, there are instances where, due to unidentified conditions that I am unable to provide precise instructions on reproducing, the scroll bar continuously expands and contracts.

For your reference, I have attached a video demonstrating the problem.

https://github.com/BoltAI/BoltAI/assets/7818591/ffbf5f7b-a265-48a8-b944-0e479cf344e8

Thank you.

**Comment by longseespace** [comment]
Thanks for reporting the issue @badrbouslikhin. I assume you don't change the scroll system setting?

![CleanShot 2023-07-18 at 15 01 46@2x](https://github.com/BoltAI/BoltAI/assets/187720/caee4450-2fa6-47b9-ba8d-546c2d91c217)

**Comment by badrbouslikhin** [comment]
<img width="827" alt="Screenshot 2023-07-18 at 10 15 40" src="https://github.com/BoltAI/BoltAI/assets/7818591/1c0dab2e-eb79-4ea1-bbce-32d042a0abb5">

Another issue in the settings page is that sometimes it doesn't display correctly when I open it. However, if I switch to another tab and then come back, it behaves as intended. Let me know if you want to create another issue for this.
<img width="822" alt="Screenshot 2023-07-18 at 10 15 08" src="https://github.com/BoltAI/BoltAI/assets/7818591/fca5708e-8117-4009-be32-f0472e0071eb">

**Comment by longseespace** [comment]
Yes, please do. I'm going to switch to a more modern Settings View and this should be fixed soon. I also think it's one of the reason for the UI performance issue on Sonoma.

**Comment by longseespace** [comment]
I think this has been fixed. Feel free to re-open if it happens again.
