### ISSUE TITLE
Visual glitches and initial message rendering in v1.12.0

### ISSUE THREAD

**Issue by kaishin** [BoltAI/BoltAI#21]
I am on Sonoma and I noticed that starting v1.12.0 the chat window is showing a lot jankier animations and has constantly visual artifacts (dividers?) as seen below.
<img width="571" alt="screenshot-2023-12-11" src="https://github.com/BoltAI/BoltAI/assets/519433/4f5396e9-7957-4a01-98fb-45cd6ea8788e">

https://github.com/BoltAI/BoltAI/assets/519433/0e981aec-f540-4657-9e1d-d3cfbc9eb68d

For the initial appearance in the chat, it would be less jarring if messages didn't expand abruptly and the view was already scrolled to the bottom on first appearance. A loader, or fade in animation could help achieve that.

**Comment by longseespace** [comment]
Hey @kaishin, I've fixed the issue with the dividers in the v1.21.1 (Xcode is to blame smh), can you upgrade and let me know if it fixes it. 

Regarding the jarring, I'm aware of the issue. This version improves the overall rendering, especially the Markdown live rendering. However it does come with this janky animation where the chat bubble takes a while to re-layout. I will find a better way to handle this.

**Comment by longseespace** [comment]
I think I've fixed both the issues in the latest version. Feel free to reopen if you still encounter these issues.
