### ISSUE TITLE
Gemini 1.5 Pro Experimental Models not showing

### ISSUE THREAD

**Issue by bwt615** [BoltAI/BoltAI#213]
**Describe the bug**
We seem to be a bit behind on Gemini Models

https://www.reddit.com/r/Bard/comments/1gwllq4/new_gemini_experimental_1121

**To Reproduce**
Choose Gemini

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - macOS: [e.g. 14.4.2]
 - app version [e.g. v1.17.2]
 - [ ] Setapp Version?

**Additional context**

**Comment by longseespace** [comment]
I've just added the exp 1121 model. Please refresh the model list to see it.

**Comment by bwt615** [comment]
Thank you!
