### ISSUE TITLE
Arrow key in GUI blocks prompt text entry

### ISSUE THREAD

**Issue by fusionmuck** [BoltAI/BoltAI#215]
**Describe the bug**
The arrow key in the prompt section can hide what is being typed.

**To Reproduce**
Please see attached screenshot.

**Expected behavior**
Please move the arrow key so that it does not cover the prompt area?

**Screenshots**
Attached.

**Version (please complete the following information):**
 - macOS: 15.2
 - app version 1.27.3 (build 124)
 - [ x ] Setapp Version? Yes

**Additional context**
No other issues observed.
![CleanShot 2024-11-28 at 12 20 26](https://github.com/user-attachments/assets/276273e0-f43c-455a-970b-da7c1aa3db80)

**Comment by longseespace** [comment]
I've fixed this in v1.29. Full release note: https://boltai.com/blog/amazon-bedrock-and-xai-support-cache-breakpoint-and-more

**Comment by fusionmuck** [comment]
Thank you for addressing this, Daniel. 

— 
/c.
