### ISSUE TITLE
Groq Missing Access to Suggested Replacement: llama-3.2-90b-vision-preview

### ISSUE THREAD

**Issue by lainath** [BoltAI/BoltAI#216]
**Describe the bug**
Following the deprecation of the “llama-3.2-90b-text-preview” model, the GroqCloud documentation recommended using “llama-3.2-90b-vision-preview” as a replacement. However, this model is unavailable in the dropdown list for selection in the application.

**To Reproduce**
	1.	Open the model selection interface in the application.
	2.     Press "Refresh"
	3.	Attempt to find “llama-3.2-90b-vision-preview” in the dropdown.
	4.	Observe that the model is missing, despite being listed as a replacement in the GroqCloud documentation.

**Expected behavior**
The “llama-3.2-90b-vision-preview” model should be available in the dropdown list, as specified in the deprecation notice for the “llama-3.2-90b-text-preview” model.

**Screenshots**
![BoltAI 2024-11-28 20 18 59](https://github.com/user-attachments/assets/6986db1c-c9b2-4dea-937d-40df4ee8d9c3)

**Version (please complete the following information):**
 - macOS: 15.1.1 (24B91)
 - app version: V1.27.3 (build 124)
 - Setapp Version: Version 3.42.0

**Additional context**
Other recent groq models also missing that are mentioned in the docs: https://console.groq.com/docs/deprecations

**Comment by longseespace** [comment]
Hi. I've updated the Groq model list. Can you refresh and try again. It should look like this:

![CleanShot 2024-11-29 at 09 37 36@2x](https://github.com/user-attachments/assets/32f78b01-03f0-438a-92b4-857db08492b7)
