### ISSUE TITLE
App icon keeps reverting to Default

### ISSUE THREAD

**Issue by stuartro** [BoltAI/BoltAI#217]
**Describe the bug**
I switch BoltAI to use the Black Panther icon but after an update the icon is reverted to the Default icon.

**To Reproduce**
1. Select Preferences > App Icon
2. Click on Black Panther. New app icon is applied.
3. Update BoltAI to a new version.
4. App icon is now Default again.

**Expected behavior**
App icon selection should persist after updating to a new version of BoltAI.

**Screenshots**

**Version (please complete the following information):**
 - macOS:15.1
 - app version v1.28.1
 - [ ] Setapp Version? N/A

**Additional context**

**Comment by longseespace** [comment]
Thanks. Have this happened before or this is the first time you encounter it? The bug is quite random, I've been struggling to reproduce it. Probably it doesn't happen on my development machine. I will take a deeper look later today.

**Comment by stuartro** [comment]
It's happened consistently for me, ever since I first started using BoltAI. Every time I update to a new version the icon reverts to the Default one (and I manually change it back to the Black Panther one).

**Comment by longseespace** [comment]
I've fixed this in v1.29. Can you confirm? Full release note: https://boltai.com/blog/amazon-bedrock-and-xai-support-cache-breakpoint-and-more

**Comment by stuartro** [comment]
HI Daniel,

 

I just updated to v1.29 and the dark icon has stayed in place 👍. Thank you for the rapid turnaround.

 

Regards,

Stuart.

 

From: Daniel Nguyen ***@***.***>
Reply-To: BoltAI/BoltAI ***@***.***>
Date: Friday, December 6, 2024 at 1:22 AM
To: BoltAI/BoltAI ***@***.***>
Cc: Stuart Robertson ***@***.***>, Author ***@***.***>
Subject: Re: [BoltAI/BoltAI] App icon keeps reverting to Default (Issue #217)

 

I've fixed this in v1.29. Can you confirm? Full release note: https://boltai.com/blog/amazon-bedrock-and-xai-support-cache-breakpoint-and-more
