### ISSUE TITLE
AI Messages broken when Markdown & Code Syntax is enabled

### ISSUE THREAD

**Issue by randomsnowflake** [BoltAI/BoltAI#221]
**Describe the bug**
If I enable "Markdown & Code Syntax" in the general settings the AI text and message bubble have the same color and thus the bots messages can't be read.
<img width="1140" alt="Screenshot 2024-12-07 at 11 03 49" src="https://github.com/user-attachments/assets/9a8665e7-8108-4279-93d3-0c5862531af7">

Disabling the checkbox shows the text again

**To Reproduce**
1. Go to Settings->General
2. Click on Markdown & Code Syntax (tick on)
3. Go to any chat or start a new one and send a message
4. See screenshot

**Version (please complete the following information):**
 - macOS: 15.1.1 (24B2091)
 - app version 1.29.0, Build 127
 - [ ] Setapp Version? -> No

**Additional context**
I installed the latest update 2-3 days ago. Before that update it worked. The problem occurs in dark and light mode. Probably unrelated to this, but setting the appearence to system (which is set to dark mode) results in weird colors.

**Comment by longseespace** [comment]
Thanks. I'll take a look. Did you change anything else recently?

**Comment by randomsnowflake** [comment]
Nope.

Three days (or so) I configured Bolt.ai and checked it works. I updated to the newest version and extended my license. I'm not sure if I tested it after updating.

**Comment by longseespace** [comment]
Hmmm I can't seem to reproduce the issue. Can you try to restart the app. If it still doesn't work, happy to jump to a call to help. My email daniel@boltai.com

![CleanShot 2024-12-07 at 11 21 39@2x](https://github.com/user-attachments/assets/c94da774-c4fc-413f-b143-9e24732357f0)

**Comment by longseespace** [comment]
Ah any chance you can share the raw message. It's unlikely to happen but the LLM might respond with html markup.

**Comment by randomsnowflake** [comment]
Look at the screenshots from the settings. This should help you pin down the issue. 

Restarting Bolt.ai did not help. 

The message is not HTML encoded. Even a simple "Hello! How can I assist you today?" is not shown.
<img width="912" alt="Screenshot 2024-12-07 at 11 25 35" src="https://github.com/user-attachments/assets/1b551a33-bf4c-4f5b-88c4-653ffe94c81f">
<img width="912" alt="Screenshot 2024-12-07 at 11 25 33" src="https://github.com/user-attachments/assets/a457c0b9-653b-4ece-85d8-0c53abc60678">

**Comment by longseespace** [comment]
Thanks I will try to test on a different Mac.

**Comment by longseespace** [comment]
I think the culprit is the Mac version. I'm upgrading to macOS 15.1.1

**Comment by longseespace** [comment]
Upgraded to 15.1.1 and it doesn't change. Do you think we can jump to a call to debug this? @randomsnowflake 

Or I could build a "debug" version to gather diagnostic data

**Comment by randomsnowflake** [comment]
I restarted my Macbook, and now it shows markdown and code correctly. I would chalk it off as a SwiftUI bug. Let me know if I can provide more information.

**Comment by longseespace** [comment]
Glad to hear it works now but TBH I don't even know how to investigate this issue. SwiftUI is like a blackbox with lot of obscure bugs.
