### ISSUE TITLE
Toggle AI command on bottom application 

### ISSUE THREAD

**Issue by zempty-zhaoxuan** [BoltAI/BoltAI#225]
# issue

Some applications cannot use the AI command because AI Comand is located at the bottom of these Applicaions, as shown in the image.

# system
macOS Sequoia 15.1.1
# applicaiton 
SideNotes, FiveNotes, BoltAI

![CleanShot 2024-12-08 at 09 31 52@2x](https://github.com/user-attachments/assets/e2cf1b89-7429-43a2-bb6f-65467e952eb9)

![CleanShot 2024-12-08 at 09 18 16@2x](https://github.com/user-attachments/assets/968fc19b-f3e7-40b7-8992-5fd18cb63f72)

**Comment by longseespace** [comment]
I've released `v1.29.4` to address this issue. Can you update and verify if it works now.
