### ISSUE TITLE
Inline Trigger for GPT Fails with API Error

### ISSUE THREAD

**Issue by sushantvema** [BoltAI/BoltAI#226]
**Describe the bug**
Inline GPT trigger worked once or twice then yielded an API error.

**To Reproduce**
try inline GPT trigger in different interfaces like Notes, Slack, neovim, etc. error happens with all task prompts

**Expected behavior**
inline trigger with `gpt: TASK_STRING_HERE` and CMD-SHIFT-ENTER should generate text without error. 

**Screenshots**
<img width="494" alt="image" src="https://github.com/user-attachments/assets/00f5f7c9-dcd4-4872-aa13-9715c356119b">

**Version (please complete the following information):**
 - macOS 14.4
 - app version v1.29.0 build 127

**Additional context**
ChatGPT works in the regular chat interfaces with my API key.

**Comment by longseespace** [comment]
Thanks. Found the issue. I was using the default AI service instead of OpenAI, which would cause this issue. Fixed and will release soon

**Comment by longseespace** [comment]
I've released `v1.29.4` to address this issue. Can you update and verify if it works now.
