### ISSUE TITLE
Prompt Stuck, Unable to Pose Follow-Up Question

### ISSUE THREAD

**Issue by armen-y** [BoltAI/BoltAI#227]
**Describe the bug**
Right in the middle of a conversation, I can no longer pose follow-up questions. The application seems to be stuck in "continue" mode. Requires re-starting BoltAI to work around.

**To Reproduce**
1. Start an Anthropic Claude 3.5 Sonnet conversation
2. Pose a question which forces Claude to break up the response.
3. Press "continue" until the LLM appears to be done with the response.
4. Attempt a follow-up question.

**Expected behavior**
Ability to pose a follow-up question.

**Observed behavior**
No ability to pose a follow-up question.

**Screenshots**
Please see this video:
![BoltAI Stuck](https://github.com/user-attachments/assets/d6e54fc9-ab50-4bfa-86b9-4063671585d5)

**Version (please complete the following information):**
 - macOS: 15.1.1
 - app version v1.29.1

**Comment by longseespace** [comment]
Ah right. Will fix soon sorry. I'm surprised  that nobody noticed this issue before including me 😅

**Comment by armen-y** [comment]
Thanks Daniel!-A.On Dec 19, 2024, at 1:59 AM, Daniel Nguyen ***@***.***> wrote:﻿
Closed #227 as completed.
