### ISSUE TITLE
Allow CMD+Enter as an Option to Replace Enter to send a request to the LLM

### ISSUE THREAD

**Issue by mlevison** [BoltAI/BoltAI#231]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when hitting <Enter> sends text to the LLM. Nearly 40 yrs of computer use have taught me <Enter> is a newline.

**Describe the solution you'd like**
Make the send command a recordable shortcut, with the default to be <Enter> then I can override it

**Describe alternatives you've considered**
There is on alternative I can currently imagine

**Comment by longseespace** [comment]
Can you disable the "Always use enter to send message"?

![CleanShot 2024-12-17 at 19 47 29@2x](https://github.com/user-attachments/assets/410e961c-f929-4aab-b70d-3ed284bff09c)

**Comment by mlevison** [comment]
Ok that was easy. I trying to figure out, why I didn't see that. 1) enter looks like a word and not a keystroke - perhaps <Enter> would have been better?

**Comment by longseespace** [comment]
You may be right. I will improve the label soon. Sorry for the issue as BoltAI has a lot of features (and options). It can be overwhelming even for power users.

**Comment by mlevison** [comment]
Daniel - no need to apologize. When the complexity of the product increases, these issues are bound to follow. I've done decades of product development. Give yourself some breathing room. When it's an opportune time, test the usability of areas of the product, like the settings dialog box.
