### ISSUE TITLE
OpenAI API key does not work after restarting the app

### ISSUE THREAD

**Issue by meltforce** [BoltAI/BoltAI#234]
**Describe the bug**

In the first chat after starting the app, I get the following error message: "Sorry, OpenAl has rejected your request.", although there is still the green light in the settings.

After pasting the exact same key into settings, it starts working again until the app is closed and started again. It is not a key issue. I changed keys some time ago and it seems that the new key is not stored persistently.

**To Reproduce**
1. Start BoltAI first time on a new day
2. Start a new Chat
3. Submit the first prompt

After pasting the exact same key in the settings, 

**Screenshots**
![CleanShot 2024-12-19 at 08 35 28@2x](https://github.com/user-attachments/assets/256c25ab-8f05-4858-abec-1372e5b314d3)

**Version (please complete the following information):**
 - macOS: [15.2]
 - app version [v1.29.1]
 - [X] Setapp Version

**Comment by longseespace** [comment]
Hi @meltforce. Can you check if the value in Keychain was correct. I think there might be an issue where BoltAI doesn't have access to the Keychain, or fetch the wrong API key and doesn't persist the correct one. 

Can you try re-grant the permission following this guide to see if it help: https://boltai.com/docs/troubleshooting/api-keys-not-persisted

Or do you use an external drive similar to this: https://github.com/BoltAI/BoltAI/issues/219

**Comment by meltforce** [comment]
Yes, this fixed the problem. I recently reinstalled Bolt, this probably broke the permission. 

Thanks and sorry for not checking the troubleshooting docs before!
