### ISSUE TITLE
Hidden Context loss in long conversations

### ISSUE THREAD

**Issue by arafatkatze** [BoltAI/BoltAI#236]
**Describe the bug**
Context loss in long conversations where Bolt AI gradually loses access to earlier messages in the chat history, effectively breaking the continuity of complex conversations.

**To Reproduce**

- Start a new chat in Bolt AI
- Copy and paste a very large file for example https://raw.githubusercontent.com/ggerganov/llama.cpp/refs/heads/master/src/llama-grammar.cpp 
- Engage in a detailed conversation with multiple back-and-forth messages (approximately 15+ messages)
- Just totally change the nature of the conversation in the middle of the chat to a totally different topic
- Reference something discussed in the earlier part of the conversation
- Observe that the AI responds as if it has no knowledge of the earlier context even though the net context size is within the models context limits

**Expected behavior**
The AI should maintain full context of the entire conversation history(as long as that is within context limit of the model itself), especially for paid Pro users. All previous messages should be included in the context window to maintain coherent, contextual conversations.

**Screenshots**
 

**Version (please complete the following information):**
 - macOS: 15.1.1 (24B91)
 - app version  v1.29.4

**Additional context**

I am a paid Pro license user who specifically uses Bolt AI as a fallback option when Claude credits are exhausted. This context loss issue severely impacts the utility of the application, as longer, complex conversations become impossible to maintain. The most concerning aspect is that this context loss happens silently without any indication to the user that earlier messages are being dropped from the context window. This creates confusion and reduces the reliability of the tool for professional use cases that require maintaining conversation context over longer periods.

**Comment by longseespace** [comment]
Can you change the "Context Limit" to "All Previous Message"? By default, BoltAI sets it to "Last 10 messages" to save cost.

![CleanShot 2024-12-28 at 09 29 33@2x](https://github.com/user-attachments/assets/a24d62b0-da10-41a7-bdae-e2b4de26a912)

**Comment by arafatkatze** [comment]
Thanks a lot
