### ISSUE TITLE
Dall-E chat session regenerating one picture causes all pictures in chat to disappear

### ISSUE THREAD

**Issue by yunapotamus** [BoltAI/BoltAI#24]
# Steps to repro
1. Open or create a Dall-E session with more than one picture response.
2. Click "Regenerate" at the bottom of the chat.

# Expected
Only the bottom picture regenerates

# Actual
*All* the pictures disappear and are replaced by spinners. However, only the bottom picture regenerates. The other pictures should not disappear.

**Comment by longseespace** [comment]
Thanks for the bug report. I'm working on a fix right now. Good news is your images are not deleted. You can find them in `~/Pictures/BoltAI`

Do you have any other suggestions for the image generation feature?

**Comment by longseespace** [comment]
I've fixed this in v1.12.3. Can you upgrade and confirm? Thanks

**Comment by yunapotamus** [comment]
Verified! Thank you for the fix. As a suggestion: I was pleasantly surprised that the images were saved in my ~/Pictures directory by default. Could there be some kind of indication in the chat UI that these images are actually being saved automatically? For a while, I was saving each one individually.

If you're looking for 'farther out' suggestions, I'm currently writing a math book using BoltAI as a research assistant. Inline LaTeX/math notation display in the chat would be amazing.

Great app, by the way.
