### ISSUE TITLE
Edits lost when switching window while editing previous message

### ISSUE THREAD

**Issue by danieldreier** [BoltAI/BoltAI#25]
version: v1.12.2 (build 32)
platform: OS X 14.1.1 (23B81)

When I edit a previous message, then switch to another application via ⌘-tab, then switch back while the edit window is still open, the edit is lost and the message is reset to the original state. This is a surprisingly big problem for my workflow because I will often work on a prompt in a text editor, and want to copy parts into an edited prompt, or copy things from a web browser.

**Comment by longseespace** [comment]
Hi @danieldreier, I confirm this is a bug. I was able to replicate it on my machine. Will fix it very soon!

**Comment by longseespace** [comment]
I've fixed this in v1.12.3. Can you upgrade and confirm? Thanks

**Comment by danieldreier** [comment]
Amazing - yes, I've upgraded, tested, and verified that this works. Thank you for turning around a fix so quickly!
