### ISSUE TITLE
Clicking on a chat / mass delete issue

### ISSUE THREAD

**Issue by wattsin** [BoltAI/BoltAI#26]
Clicking on an existing chat will highlight it but it then become unfocused causing the user to have to click it again to be able to hit the "delete" key - this is mainly a problem when trying to delete old chats, I need to click it once and then again to be able to delete it. A mass deletion option or shift select would also be useful.

**Comment by longseespace** [comment]
This is a tricky issue. So we need to pick either:

1. Automatically focus on the chat input field when clicking on a chat OR
2. Don't do that and we can select multiple chat row

> A mass deletion option or shift select would also be useful.

It should be working already. Unless there was a bug.

![CleanShot 2023-12-28 at 22 52 23@2x](https://github.com/BoltAI/BoltAI/assets/187720/ece021bb-a9bd-4ea3-a0e0-ddd51f4c3cd4)

**Comment by wattsin** [comment]
I just updated and mass selection is working now - the clicking on a chat and then focusing on the input is still the flow. But with shift select it's no longer as annoying to delete old chats. This can be closed
