### ISSUE TITLE
Message clears when switching message history

### ISSUE THREAD

**Issue by danieldreier** [BoltAI/BoltAI#27]
Reproduction steps:

1) create two New Chats
2) In the first chat, type "foo" into the message (but do not send it)
3) switch to the second New Chat
4) switch back to the first chat. Observe that the chat message box is empty.

The reason this is a problem for my workflow is that I use it to write code and documentation, and sometimes want to copy things from one chat session to another, so I relatively frequently have partially completed prompts which get lost.

BTW - Thank you for this very helpful tool!

**Comment by longseespace** [comment]
Ah right. This was my pet peeve too. Will fix soon, Daniel.

**Comment by longseespace** [comment]
I've fixed this in v1.13.0. Can you confirm? Thanks

https://boltai.com/changelogs/v1.13
