### ISSUE TITLE
chat GPT-4 give me weird responses, outdated responses

### ISSUE THREAD

**Issue by alexwenzel** [BoltAI/BoltAI#28]
I am asking about nuxt.js v3. The chatGPT Web client has some other answers then this.

For me, it looks like it does not use chatGPT-4.

## Screenshots of Problem

<img width="886" alt="image" src="https://github.com/BoltAI/BoltAI/assets/3659928/b149aba5-54f9-4b8f-9f38-07e1ea75b9f1">

<img width="795" alt="image" src="https://github.com/BoltAI/BoltAI/assets/3659928/6fad65f4-b877-4563-8794-23925dbf95e4">

<img width="865" alt="image" src="https://github.com/BoltAI/BoltAI/assets/3659928/3eb5e307-a7c8-4788-94c5-3b69238f2560">

## This are my settings

<img width="336" alt="image" src="https://github.com/BoltAI/BoltAI/assets/3659928/57af1ffa-c8b4-4146-9b94-ae82cdc2f736">

<img width="360" alt="image" src="https://github.com/BoltAI/BoltAI/assets/3659928/a8105ac4-0c52-498a-a77c-d926869e2d76">

## Final question

Am I wrong with some setting?

**Comment by longseespace** [comment]
Hi @alexwenzel. That was correct. The chatgpt web uses GPT-4 Turbo, not **GPT-4**

You can choose to use GPT-4 Turbo in BoltAI.

In my experience, GPT-4 gives a much better answer related to coding. Though it’s not up-to-date as the Turbo model. 

You can learn more about these models and it cut off dates here: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by alexwenzel** [comment]
thank you for your answer. i will and hope for the best!!

all the best 👍
