### ISSUE TITLE
Dark text foreground color is black

### ISSUE THREAD

**Issue by suntereo** [BoltAI/BoltAI#29]
I really like Bolt AI but have had an issue that is still there. I prefer to set the theme to dark:

<img width="788" alt="Xnip2024-01-16_13-49-31" src="https://github.com/BoltAI/BoltAI/assets/171720/34b38501-c360-471a-9c64-db1d44bd2c8f">

But when I do this and type in the text box, the foreground text appears to be solid black and unreadable:
<img width="692" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/c872bfb3-fe3b-4a38-b75e-73bf499b571b">

The preview text looks good:
<img width="722" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/a356d19c-eeb1-4320-9404-0e181ea63ed3">

The issue is when you type text in--it's just unusable

**Comment by longseespace** [comment]
Thanks. Will fix very soon!

**Comment by longseespace** [comment]
@suntereo which version are you on? I tried but cannot replicate the issue. Any other settings on your machine that would cause it?

Here is how it looks for me:

![CleanShot 2024-01-17 at 12 54 18@2x](https://github.com/BoltAI/BoltAI/assets/187720/e96dc972-5cfa-4c86-80e3-7d39230b4de2)

**Comment by suntereo** [comment]
Weird! I'm on: 
<img width="130" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/f503fa9f-4b54-4e77-b2a4-1da8ac932c9d">

I noticed this works:
<img width="341" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/f01e6e86-a122-4b1c-9f10-3168575dd731">

And other text boxes on the settings screen work... just not the main prompt textbox. Do you have any ideas of what other settings on my machine could cause this?

**Comment by longseespace** [comment]
That's the latest version. Are you on mac Sonoma?

**Comment by suntereo** [comment]
No, I'm on Ventura 13.6.1. My 2017 iMac is too old to run Sonoma :(

**Comment by longseespace** [comment]
Ah thanks. That's probably why. I will test more on the Ventura virtual machine.

**Comment by longseespace** [comment]
I tried on Ventura and still couldn't replicate it. I will try to set the text color explicitly in the next version to see if it could fix it for you.

![CleanShot 2024-01-19 at 13 49 51@2x](https://github.com/BoltAI/BoltAI/assets/187720/b986330f-94c9-4249-b2a0-6912db9417e6)

**Comment by suntereo** [comment]
Ok thanks for all your help!

**Comment by suntereo** [comment]
It's working now... thanks!

<img width="532" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/ac1512c2-e569-4e57-b1b2-fc35039027ea">
