### ISSUE TITLE
UI artifact on settings page open

### ISSUE THREAD

**Issue by badrbouslikhin** [BoltAI/BoltAI#3]
The settings page sometimes doesn't display correctly when I open it.
However, if I switch to another tab and then come back, it behaves as intended.
<img width="822" alt="Screenshot 2023-07-18 at 10 15 08" src="https://github.com/BoltAI/BoltAI/assets/7818591/983974ae-6637-46c1-bacf-1b9bca3342f9">

**Comment by longseespace** [comment]
Fixed in the latest version.
