### ISSUE TITLE
Web Browsing plugin not working with GPT-4 vision

### ISSUE THREAD

**Issue by juandrei** [BoltAI/BoltAI#30]
v1.13.1 (build 35)
Took a screenshot and asked to relate it to a url.  It refused.  Even when explicitly asking to use "Web Browsing" plugin the response is: "I'm sorry for any confusion, but as an AI developed by OpenAI, I don't have the ability to browse the web or access content from live websites."  Is there a workaround to use screenshot with web browsing, or better yet, also with web search?

**Comment by longseespace** [comment]
Sorry. This is a limitation of the Vision model and there is nothing I could do (no functions/tools available)

> Currently, GPT-4 Turbo with vision does not support the message.name parameter, functions/tools, response_format parameter, and we currently set a low max_tokens default which you can override.

https://platform.openai.com/docs/guides/vision

**Comment by longseespace** [comment]
A workaround I think is to use the vision model first, then switch to a text model (GPT-4 turbo) and enable the plugins
