### ISSUE TITLE
Mistral

### ISSUE THREAD

**Issue by Kinkazma** [BoltAI/BoltAI#31]
![PPP](https://github.com/BoltAI/BoltAI/assets/67934749/b73b4c0d-6daa-42cb-b5fd-31a45ffc457b)

Rien ne s'affiche, la clef API est bonne, et c'est bien facturé...
Avec ou sans les plugins. J'ai suivi aussi le guide pour verifier.

**Comment by longseespace** [comment]
Hi. It's likely that you haven't entered a payment method / topped up credits in Mistral yet.

Can you do that and try again?

**Comment by longseespace** [comment]
Hey @Kinkazma, I've fixed this in v1.14.1. Please upgrade
