### ISSUE TITLE
Collapsing folders causes sidebar list to render incorrectly

### ISSUE THREAD

**Issue by yunapotamus** [BoltAI/BoltAI#32]
# Steps

1. Create several folders, and include some chats in the sidebar under the folders that you create
2. Collapse any of the folders

# Expected
Folder collapses as normal

# Actual
Folder collapses, but the names of the items in the sidebar are messed up. In particular, the folder name appears below where it should be. In the screenshot, "Travel" and "Health" are several rows below where they should be.

<img width="1029" alt="Screenshot 2024-01-26 at 4 42 10 PM" src="https://github.com/BoltAI/BoltAI/assets/28821219/cf1cb1db-0f8b-412d-acb1-9d5dd82872f5">

**Comment by yunapotamus** [comment]
Love the new folders feature btw.

**Comment by longseespace** [comment]
Thanks for reporting, Yuna. Working on the fix right now.
