### ISSUE TITLE
Code is white on white and other visual glitches

### ISSUE THREAD

**Issue by neominik** [BoltAI/BoltAI#35]
Bolt mostly works great, however, code in user prompts is unreadable, because it is rendered with white text on a white background when using the light theme. Changing fonts or specific themes in the appearance section (where spacing is pretty goofy) don't seem to apply at all. Only solution for now is always using dark theme. See screenshots below.
![Screenshot 2024-02-26 at 15 58 07](https://github.com/BoltAI/BoltAI/assets/22345027/fc6db4b6-16d3-4536-b8a2-369bbb3978c5)

![Screenshot 2024-02-26 at 15 56 38](https://github.com/BoltAI/BoltAI/assets/22345027/5540785e-ac75-4061-9764-6719ffd31366)

**Comment by longseespace** [comment]
Thanks. I will update the color scheme for the user message 😅 

Are you on the latest version?

**Comment by neominik** [comment]
Yes, I am on 1.14.0

**Comment by longseespace** [comment]
I decided to render user message as plaintext. Here is my rationale: https://boltai.canny.io/feature-requests/p/render-user-message-prompt-as-plain-text

Let me know what you think
