### ISSUE TITLE
Something about the accessability settings stopped Cmd+R working in firefox

### ISSUE THREAD

**Issue by d5ve** [BoltAI/BoltAI#36]
Thank you for BoltAI, I use it every day.

I noticed that the Cmd+R keyboard shortcut (reload page) stopped working in Firefox after installing BoltAI, and enabling the accessability settings. I couldn't see anything obvious like BoltAI registering that shortcut for itself.

Cmd+Shift+R (reload page without cache) still worked in Firefox.

I disabled the accessability settings for BoltAI and things got weird and I had to restart my laptop. My magic mouse clicks stopped registering and I had to open the laptop and use the mouse and keyboard there to shut things down.

After the restart, Cmd+R is working again.

Macbook Pro 13" 2019
Macos 14.2.1 (23C71)
Firefox 123

**Comment by longseespace** [comment]
Hey Dave. Sorry for the issue. There is a weird bug in macOS with the Accessibility permission I think. I tried to remove BoltAI permission sometimes and it caused kernel panic. Super weird.

Anyway, I think the issue you got is from the new version where I added support for customizable shortcut key. But looks like it's global and not app-only. 

I will investigate further and issue a fix soon.

**Comment by longseespace** [comment]
I've reverted the change in v1.14.1. It should works normally now.

**Comment by d5ve** [comment]
Many thanks @longseespace!
