### ISSUE TITLE
Search plugin does not work with mistral-8x7b

### ISSUE THREAD

**Issue by juandrei** [BoltAI/BoltAI#38]
I use mistral-8x7b which works great by itself.  However, I was expecting it to be able to also use the web browse and web search plugins.  Those do NOT work unfortunately.

**Comment by longseespace** [comment]
Thanks for bringing this up. The way these plugins work is that it uses `function calling` which only available for OpenAI models when it was introduced.

Now I can see that more models supporting function calling, and I will add these capability to these models too.

I can see that Mistral does support function calling, according to this doc: https://docs.mistral.ai/guides/function-calling/

However it's unclear that they guarantee the support in their API offering (no mention of support here):
 https://docs.mistral.ai/api/#operation/createChatCompletion

**Comment by juandrei** [comment]
Looking forward to your new support of function calling.  It would make a great difference!

**Comment by longseespace** [comment]
I think this has been implemented.
