### ISSUE TITLE
Web search plugin results

### ISSUE THREAD

**Issue by juandrei** [BoltAI/BoltAI#39]
Is there a way to specifically get the web search to look into 5, 10, 20 results?

**Comment by longseespace** [comment]
Not yet. I'm reworking the plugin system to make it 100% independent with the main app. Currently it's part of the app and it's difficult to tweak the behavior.

**Comment by juandrei** [comment]
As models become evenly capable of routine tasks, then "web search" options and "web browsing" enhancements will make a big difference for real-time applications.

**Comment by longseespace** [comment]
Actually I check the code and this should be working. Can you confirm?

![CleanShot 2024-04-24 at 03 17 32@2x](https://github.com/BoltAI/BoltAI/assets/187720/9d401350-910c-472c-ba85-cad7ac91b307)
