### ISSUE TITLE
Pressing the new chat button does not open the chat textbox

### ISSUE THREAD

**Issue by riogesulgon** [BoltAI/BoltAI#4]
![image](https://github.com/BoltAI/BoltAI/assets/38380494/379d3156-bc27-4391-b3a6-e4ef37b21050)
When I try to create a new chat using the new chat button, there is no way for me to type my new text. What I end up doing is clicking an existing message and then click the new chat to open up the textbox for me type in.

**Comment by longseespace** [comment]
Thanks for reporting. Can you share your OS & app version? @riogesulgon

**Comment by riogesulgon** [comment]
![image](https://github.com/BoltAI/BoltAI/assets/38380494/3f79557e-5ca9-4494-8410-3713e76727e3)

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	9 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	1968.100.17.0.0 (iBridge: 20.16.4252.0.0,0)
  OS Loader Version:	540.120.3~22

**Comment by riogesulgon** [comment]
![image](https://github.com/BoltAI/BoltAI/assets/38380494/127129ce-b923-4a50-aaf5-c00590d33a78)
App version

**Comment by longseespace** [comment]
Thank you. I will take a deeper look and get back to you soon, Rio.

Though I don’t think it’s fixed yet, you definitely should update to the
latest version (v1.8)

I’ve added a lot of new and exciting features:

https://boltai.com/changelogs/v1.8

Thanks,

*Daniel Nguyen*
Founder — BoltAI

***@***.*** ***@***.***>
*https://BoltAI.app <https://boltai.app>*

**Comment by longseespace** [comment]
Does the issue still happen @riogesulgon?

**Comment by longseespace** [comment]
I've fixed this in v1.10 https://boltai.com/changelogs/v1.10. Feel free to reopen if the issue still persists
