### ISSUE TITLE
Feature Request: Support for Gemini 1.5 API key?

### ISSUE THREAD

**Issue by suntereo** [BoltAI/BoltAI#40]
Hi! Would be amazing if Bolt AI allowed us to add Gemini 1.5 API key here:

<img width="795" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/39df08fc-93e4-485e-a292-d61f72758a25">

...
<img width="1103" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/0add1aa0-5a01-4f1e-9397-7a9a16e2c9c5">

Are there any plans in the works for this?

**Comment by longseespace** [comment]
Hey Shawn. I've added this in the latest version.

**Comment by suntereo** [comment]
Thank you!!! 

I successfully have it working for Gemini 1.0:

<img width="492" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/de260c51-f532-450a-918c-2243e9003f4e">

But it's throwing an error for 1.5:

<img width="526" alt="image" src="https://github.com/BoltAI/BoltAI/assets/171720/9805e895-42d5-4355-aa00-8c672a98e036">

 I'm guessing they aren't allowing API use for that just yet
