### ISSUE TITLE
Toggling BoltAI will delete prompt

### ISSUE THREAD

**Issue by zouloux** [BoltAI/BoltAI#43]
Hi there,
When using activate toggle shortcut, if we use it to close the window, the prompt is discarded.
Can we keep the current prompt in memory to have it back when re-opening the window ?
It's useful to discard the current window for a quick google search or copy-pasting a text from an email for example.

**How to reproduce :**
- Set keyboard shortcut for "Activate BoltAI Chat" in settings.
- Open a new chat, start a prompt, do not send it.
- Hit activate keystroke. ( BoltAI window should close )
- Hit the keystroke again

-> The windows open to the last chat, but the prompt has been deleted. 

Thanks

**Comment by zouloux** [comment]
Maybe just hiding the window instead of destroy / recreating it would patch the issue ? I don't know if it's better between memory and CPU usage.

**Comment by longseespace** [comment]
Ah gotcha. I will find a better solution. You're right, currently it destroys the window and the prompt would be gone. There was a critical memory leak issue before if the window is not destroyed so it would avoid retaining the window if possible. 

Will try to find a better way to store the pending prompt.

**Comment by longseespace** [comment]
I've fixed this in v1.15.5. I decided to hide/unhide the window instead of destroying it.

**Comment by zouloux** [comment]
Yeah cool ! When I have the hide dock icon option checked, it's not in the CMD + tab list so it's perfect know.
Aside note, I could not upgrade from the *.1 version I guess ( don't remember ), the "Check for update" was not in the menu, and it did not checked at startup. I had to redownload the whole app. Maybe you have users stuck on this version as well. I can create a ticket but it will be basically impossible for me to test it.

**Comment by longseespace** [comment]
Yeah there was a bug in previous version. There is the option to Check for updates from the App Menu Bar though but I agree, it's hard to discover. I might need to send an email reminder about this.

Thanks

**Comment by zouloux** [comment]
That's the issue I had. No auto update but also not button in app menu bar :
<img width="338" alt="image" src="https://github.com/BoltAI/BoltAI/assets/739001/3eeb739d-187d-43b6-90be-2c9456e99423">
( this item was missing )

**Comment by zouloux** [comment]
I removed the dmg from my download directory. I think it may was **1.15.1** if it can help. I hope I was just tired 😅. Thanks again and good luck ✌️

**Comment by longseespace** [comment]
No you were right. There was a version affected by this bug but I've fixed it now. I was reffering to this Menu Bar Icon

![Image](https://canny.io/images/962d5dd5ecfbff36e5ef107f420e4ee2.jpg)

**Comment by zouloux** [comment]
Ooooooh. That why I didn't find it ! Hopefully it's patched now.
Cheers ✌️
