### ISSUE TITLE
Unable to send picture to claude 3 / gpt4 in the inapp chat

### ISSUE THREAD

**Issue by mortimerprimes** [BoltAI/BoltAI#44]
Unable to send picture to claude 3 / gpt4 in the inapp chat

**Comment by longseespace** [comment]
Thanks. Currently, BoltAI only support text message for Claude 3. But it should work for GPT-4 Vision. Can you share more on steps to replicate your issue? Thanks

**Comment by longseespace** [comment]
Following up on this @mortimerprimes
