### ISSUE TITLE
Display website URL

### ISSUE THREAD

**Issue by ThibautPV** [BoltAI/BoltAI#45]
If we add an url in message box (ex : [my-website.com](http://my-website.com/)), it is not visible (link color is blue and background color is blue too)

<img width="546" alt="Capture d’écran 2024-03-11 à 09 04 58" src="https://github.com/BoltAI/BoltAI/assets/75485473/b60e2b9a-67d0-4d00-8093-b14dd484361c">

**Comment by longseespace** [comment]
Thanks. I've fixed this and will release a new version soon

**Comment by longseespace** [comment]
I decided to render user message as plaintext. Let me know what you think.

**Comment by ThibautPV** [comment]
OK. Thanks
