### ISSUE TITLE
[REQUEST] : Add Shortcut to delete Chat

### ISSUE THREAD

**Issue by ThibautPV** [BoltAI/BoltAI#47]
Can we introduce shortcuts (such as ⌘ + ⌫) to remove a selected chat conversation?

**Comment by longseespace** [comment]
> Can we introduce shortcuts (such as ⌘ + ⌫) to remove a selected chat conversation?

You can select a chat (or multiple) and press `Delete` to remove chat. Would it work for you?

**Comment by ThibautPV** [comment]
Yes. Perfect ! Thank you
