### ISSUE TITLE
Unable to check for updates on v1.15.2

### ISSUE THREAD

**Issue by 247arjun** [BoltAI/BoltAI#53]
There used to be an option in the menubar that would allow me to check for updates, but that option is missing since v1.15.2

<img width="162" alt="image" src="https://github.com/BoltAI/BoltAI/assets/20020129/49db7f97-e97a-4029-8ba6-ef7da88c99d4">

**Comment by 247arjun** [comment]
I ended up manually downloading the DMG from [the app's website](https://boltai.com) and the updated v1.15.4 has that option again.
<img width="214" alt="image" src="https://github.com/BoltAI/BoltAI/assets/20020129/2399b767-8c87-404e-870b-615ab845b815">

**Comment by longseespace** [comment]
Thanks. Yeah, I made a mistake in v1.15.2 but it's now fixed.
