### ISSUE TITLE
Trying to add "Groq" AI Service leads to OpenAI error message

### ISSUE THREAD

**Issue by tobias-walle** [BoltAI/BoltAI#54]
I was trying to add the "Groq" AI Service. After adding the key and saving I get the following error message.

> Sorry, OpenAl has rejected your request. Here is the error message from OpenAl: The model 'llama2-70b-4096* is not active.

<img width="791" alt="image" src="https://github.com/BoltAI/BoltAI/assets/9933601/51a5f2fd-60ef-4d49-a6f1-c91cf77dfe52">

**Comment by longseespace** [comment]
Hey @tobias-walle, looks like the llama2 model is currently offline. And there is a bug on BoltAI that prevent saving the key.

I'm working on the fix right now. Also, adding support for `gemma`.

Sorry for the issue

![CleanShot 2024-03-29 at 15 37 28@2x](https://github.com/BoltAI/BoltAI/assets/187720/eba79130-85c9-4b34-b7b5-2d415cf41262)

**Comment by tobias-walle** [comment]
Thank you for the fast response! 

As a workaround I was able to add the model as a OpenAI-Compatible Server
<img width="562" alt="image" src="https://github.com/BoltAI/BoltAI/assets/9933601/db06f3b8-a820-4faf-a569-26648338ccb3">

**Comment by longseespace** [comment]
Smart! I didn't think about that haha 😅

**Comment by longseespace** [comment]
I've fixed this in the latest version (v1.15.5). Feel free to reopen the issue if the problem persists :D

**Comment by tobias-walle** [comment]
Thank you! I can confirm it works now 🙂
