### ISSUE TITLE
`cmd-n` doesn't use default model

### ISSUE THREAD

**Issue by sourdoughdev** [BoltAI/BoltAI#56]
When setting the default model, `cmd-n` doesn't use the default model. The new button does, just not the shortcut.

https://github.com/BoltAI/BoltAI/assets/52873796/af7bbcc4-84dc-4eb1-bce9-04ab13fbb80b

**Comment by longseespace** [comment]
Thanks. I confirm this is a bug. Working on a fix rn

**Comment by longseespace** [comment]
I've fixed this in v1.15.6. Please update and confirm. Thx

**Comment by sourdoughdev** [comment]
Fixed, thanks!
