### ISSUE TITLE
Keyboard shortcut trigger opens settings

### ISSUE THREAD

**Issue by bwt615** [BoltAI/BoltAI#58]
Whether this was intended behavior or not, I manage to trigger the app settings with the keyboard shortcut. Really cramps the workflow. Maybe fix or add a setting for it?

**Comment by longseespace** [comment]
Looks like it’s a bug. I’m working on the fix rn

**Comment by bwt615** [comment]
Thank you!

**Comment by longseespace** [comment]
I've fixed this in v1.15.6, please update.

**Comment by bwt615** [comment]
Thank you!!

**Comment by bwt615** [comment]
Few thoughts:


  1.  Claude 3 code blocks are broken, super frustrating, some code exists outside of the block consistently
  2.  Copy and paste from excel results in an image which I haven’t been able to see a single model handle. Think you should convert to markdown

[Benjamin Thomas]
Benjamin Thomas
Mobile: +1 (781) 864-3648 | Fax: +1 (781) 787-2609
Email: ***@***.******@***.***> | Book: My Calendar<http://book.bthomas.io/> | Website: BThomas.io<http://bthomas.io/>
Twitter: @benjaminwthomas<https://twitter.com/benjaminwthomas> | LinkedIn: benjaminwesleythomas<https://www.linkedin.com/in/benjaminwesleythomas/>


From: Daniel Nguyen ***@***.***>
Date: Tuesday, April 2, 2024 at 3:16 AM
To: BoltAI/BoltAI ***@***.***>
Cc: Benjamin Thomas ***@***.***>, Author ***@***.***>
Subject: Re: [BoltAI/BoltAI] Keyboard shortcut trigger opens settings (Issue #58)

I've fixed this in v1.15.6, please update.

**Comment by longseespace** [comment]
Hi.

> Claude 3 code blocks are broken, super frustrating, some code exists outside of the block consistently
> Copy and paste from excel results in an image which I haven’t been able to see a single model handle. Think you should convert to markdown

Can you share a screenshot and your prompt so I could debug it faster.

**Comment by bwt615** [comment]
[Image.png]

The prompt if needed, part of larger convo. You win for responsiveness!!!!

let’s just do this let Source = Json.Document(Web.Contents("https://api.asinaria.xyz/powerbi/json/oBNPd6")), #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error), #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Id", "Name", "Text Content", "Description", "Status", "Date Created", "Date Updated", "Date Closed", "Date Done", "Creator", "Assignees", "Tags", "Parent", "Priority", "Due Date", "Start Date", "Points", "Time Estimate", "Asignee (No ClickUp)", "LOB", "Progress", "Project Description", "Project Status", "Sort", "Url", "List", "Project", "Folder", "Task Type", "Last Comment"}, {"Id", "Name", "Text Content", "Description", "Status", "Date Created", "Date Updated", "Date Closed", "Date Done", "Creator", "Assignees", "Tags", "Parent", "Priority", "Due Date", "Start Date", "Points", "Time Estimate", "Asignee (No ClickUp)", "LOB", "Progress", "Project Description", "Project Status", "Sort", "Url", "List", "Project", "Folder", "Task Type", "Last Comment"}), #"Expanded Progress" = Table.ExpandRecordColumn(#"Expanded Column1", "Progress", {"percent_complete"}, {"Progress.percent_complete"}), #"Changed Type" = Table.TransformColumnTypes(#"Expanded Progress",{{"Id", type text}, {"Name", type text}, {"Text Content", type text}, {"Description", type text}, {"Status", type text}, {"Date Created", type datetime}, {"Date Updated", type datetime}, {"Date Closed", type datetime}, {"Date Done", type datetime}, {"Creator", type text}, {"Assignees", type text}, {"Parent", type text}, {"Due Date", type datetime}, {"Start Date", type datetime}, {"Points", type any}, {"Time Estimate", type any}, {"Asignee (No ClickUp)", type any}, {"LOB", type any}, {"Progress.percent_complete", Int64.Type}, {"Project Description", type any}, {"Project Status", type text}, {"Url", type text}, {"List", type text}, {"Project", type text}, {"Folder", type text}, {"Task Type", type text}}),

// Group and aggregate Project_SubTasks_Completed table
#"Grouped Completed_SubTasks" = Table.Group(Project_SubTasks_Completed, {"Next Project Parent"}, {{"Completed_SubTasks", each Text.Combine(List.Transform([Name], each "- " & _), ", "), type text}}),

// Group and aggregate Project_SubTasks_Upcoming table
#"Grouped Upcoming_SubTasks" = Table.Group(Project_SubTasks_Upcoming, {"Next Project Parent"}, {{"Upcoming_SubTasks", each Text.Combine(List.Transform([Name], each "- " & _), ", "), type text}}),

// Merge aggregated subtask tables with main Projects table
#"Merged Completed_SubTasks" = Table.NestedJoin(#"Changed Type", {"Id"}, #"Grouped Completed_SubTasks", {"Next Project Parent"}, "Completed_SubTasks", JoinKind.LeftOuter),
#"Expanded Completed_SubTasks" = Table.ExpandTableColumn(#"Merged Completed_SubTasks", "Completed_SubTasks", {"Completed_SubTasks"}, {"Completed_SubTasks"}),

#"Merged Upcoming_SubTasks" = Table.NestedJoin(#"Expanded Completed_SubTasks", {"Id"}, #"Grouped Upcoming_SubTasks", {"Next Project Parent"}, "Upcoming_SubTasks", JoinKind.LeftOuter),
#"Expanded Upcoming_SubTasks" = Table.ExpandTableColumn(#"Merged Upcoming_SubTasks", "Upcoming_SubTasks", {"Upcoming_SubTasks"}, {"Upcoming_SubTasks"})
in #"Expanded Upcoming_SubTasks"

with newlines instead of commas. we also mave have loss these lines, can you add them in after changed type?

    #"Appended Query" = Table.Combine({#"Changed Type", #"Projects Pivot"}),
    #"Added Custom" = Table.AddColumn(#"Appended Query", "Priority Int", each if [Priority] = "urgent" then 1 else if [Priority] = "high" then 2 else if [Priority] = "normal" then 3 else if [Priority] = "low" then 4 else null)


[Benjamin Thomas]
Benjamin Thomas
Mobile: +1 (781) 864-3648 | Fax: +1 (781) 787-2609
Email: ***@***.******@***.***> | Book: My Calendar<http://book.bthomas.io/> | Website: BThomas.io<http://bthomas.io/>
Twitter: @benjaminwthomas<https://twitter.com/benjaminwthomas> | LinkedIn: benjaminwesleythomas<https://www.linkedin.com/in/benjaminwesleythomas/>
________________________________

**Comment by longseespace** [comment]
Sorry can you attach the image on Github. Replying via email doesn’t seem to upload the image. Thanks
