### ISSUE TITLE
App crashing on some chats

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#6]
Not sure how to title this properly but there are certain old chats, which when I try to write any new messages to, the app crashes. Even if I fork that chat onto a new one, it still crashes.

I am not entirely sure how to reproduce it. But perhaps it could have something to do with changing parameters like system message, temperature, context limit , etc after the chat had already started and gone on for a while. Even if changing parameters is the culprit, I am not sure which of the parameters is the cause or if any of them would cause the same issue.

I have experienced this using OpenRouter models, not sure if it occurs to OpenAI direct models or not.

Here's the crash log if it helps:
https://www.mashupstack.com/share/6517d4631bedf

Edit: I just had a crash without changing any parameters, so that may not be what's causing it

**Comment by longseespace** [comment]
I think this has been fixed. Feel free to re-open if it happens again.
