### ISSUE TITLE
Loading spinner persists when creating a new chat after reopening with collapsed sidebar

### ISSUE THREAD

**Issue by zchlm** [BoltAI/BoltAI#60]
### Steps to Reproduce

1. Collapse the chat sidebar.
2. Close the BoltAI application.
3. Reopen the BoltAI application.
4. Attempt to create a new chat.

### Expected Behavior

Upon creating a new chat, the chat interface should appear, allowing the user to start a new conversation.

### Actual Behavior

Instead of displaying the new chat interface, a loading spinner appears indefinitely, preventing the user from starting a new chat.

![Screenshot 04-04-2024 at 11 37 47@2x](https://github.com/BoltAI/BoltAI/assets/8256446/4ab9e18a-049b-42a0-9afb-77201a39fb1d)

**Comment by longseespace** [comment]
Thanks. Are you on macOS 13+? On macOS 12, I have to use the [NavigationView](https://developer.apple.com/documentation/swiftui/navigationview) which is deprecated and super buggy.

On macOS 13, I will switch to a new implementation soon.

**Comment by zchlm** [comment]
@longseespace I'm on Mac 14.4. But it's no longer an issue on later versions of Bolt so I'll close this issue.
