### ISSUE TITLE
AI Command doesn't respect default model.

### ISSUE THREAD

**Issue by kocyigityunus** [BoltAI/BoltAI#61]
Whenever I try to use AI Commands, it chooses openai gpt3.5. but the default model is ollama:phi

**Comment by longseespace** [comment]
Thanks for the bug report. When you use an AI Command, BoltAI will attempt to use the AI provider in its configuration first.

Can you update the AI Command's configuration and try again?

Thanks

![CleanShot 2024-04-09 at 14 49 39@2x](https://github.com/BoltAI/BoltAI/assets/187720/9a261edb-0f8f-4d52-a340-0fa0b1e4c5a6)

**Comment by kocyigityunus** [comment]
Can you add the "same as default model" option there? Because I change my default model nearly every day.

**Comment by longseespace** [comment]
> Can you add the "same as default model" option there? Because I change my default model nearly every day.

Great idea! I will add this in the next version. Maybe I will use it as default too.
