### ISSUE TITLE
Unable to change API provider

### ISSUE THREAD

**Issue by fjb4** [BoltAI/BoltAI#63]
I have BoltAI configured to use OpenAI, Anthropic, and Google with Anthropic set as the default. New chat windows used to open up with Anthropic correctly selected and I was able to easily change to another API provider, if I wanted to.

In one of the recent releases, this stopped working. Now, when I open a chat window, it looks like this:
![Screenshot 2024-04-10 at 14 21 00](https://github.com/BoltAI/BoltAI/assets/158116/22548aa2-6700-4ed0-b99b-5421bac2cf05)

Notice it shows that OpenAI is the provider but Claude 3 is the selected model.

If I click the button in the top-left corner of the chat window, it shows this:
![Screenshot 2024-04-10 at 14 24 44](https://github.com/BoltAI/BoltAI/assets/158116/ef303df1-c27b-4082-9c34-00988d010c20)

If I try to switch providers, the list only shows OpenAI:
![Screenshot 2024-04-10 at 14 22 17](https://github.com/BoltAI/BoltAI/assets/158116/65cbd290-ea2f-47f3-83f0-99d71091619e)

And this is despite having OpenAI, Anthropic, and Google all configured in my settings.

Again, all this was working properly, but something must have changed in one of the recent updates.

Otherwise, I'm really enjoying using BoltAI. And if there's any more information I can share that would help tracking down this issue, let me know.

**Comment by longseespace** [comment]
Sorry for the issue. I thought I fixed this in v1.15.8 but looks like it doesn’t work. 

I will take a deeper look. 

Can you go to Settings > Models and set OpenAI as default to see if it fixes it. 

Some users reported that it would work with this trick

**Comment by fjb4** [comment]
I changed OpenAI to be the default, and now new chat windows do start off with OpenAI selected but I still can't change to another API provider:
![Screenshot 2024-04-10 at 14 39 48](https://github.com/BoltAI/BoltAI/assets/158116/88576696-47fa-439b-a527-3c10bc9d56a4)

**Comment by longseespace** [comment]
I couldn't replicate the issue. Any chance you could help me replicate it? 😅 @fjb4

**Comment by longseespace** [comment]
Meanwhile, please use the Chat Setting button (next to the chat name)

**Comment by longseespace** [comment]
Actually I found the root cause. It is indeed a bug. Follow this workaround:

1. Go to **Settings > Models**
2. Select each AI provider and then save it again.

I recently added the `isValid` field to these AI service records (so it would not show invalid AI services which might be confusing). But it does not backfill the previous records and causes this issue.

Sorry, going to issue a fix soon.

**Comment by longseespace** [comment]
I've fixed this in v1.15.9. Can you confirm? :D

**Comment by fjb4** [comment]
Yep, that fixed it! Thanks for getting to it so quickly.
