### ISSUE TITLE
azure support

### ISSUE THREAD

**Issue by yqiang** [BoltAI/BoltAI#64]
I couldn't figure out how to get BoltAI to work with a custom Azure endpoint. Specifically, when you deploy an Azure OpenAI instance, you give it a name like "gpt-4" or whatever you want. I couldn't find a way to specify this in the UI, since the list of models is a drop down.

**Comment by longseespace** [comment]
Hi. To do that, go to **Settings > Models**, then click the plus (+) button. Choose "**Azure OpenAI**".

Fill the form then click Save.

Make sure the URL is correct. It must include the `api-version` like this screenshot.

Cheers,

![CleanShot 2024-04-12 at 21 11 38@2x](https://github.com/BoltAI/BoltAI/assets/187720/4f46cb93-1fa2-45ed-b499-f3eda57386ab)

**Comment by yqiang** [comment]
Thanks, that totally worked. For whatever reason I missed the "Read guide" button right below it. It might be useful to remove the "Model:" drop down, singe the endpoint specifies the model that'll be used.

**Comment by xueyixingbang** [comment]
Thanks, that's very helpful.  In the future, one can refer here for questions about API versions：
https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation
