### ISSUE TITLE
Font size in text entry boxes does not obey font size settings

### ISSUE THREAD

**Issue by kyouens** [BoltAI/BoltAI#65]
<img width="1414" alt="Screenshot 2024-04-11 at 8 58 06 PM" src="https://github.com/BoltAI/BoltAI/assets/1498595/691c5339-b3ca-4eef-ba76-aa3ad9546990">

**Comment by longseespace** [comment]
Thank you. Quick question, @kyouens, would you prefer to use the same font size for both input text and the chat bubble text, or would you prefer them to be 2 different settings?

**Comment by kyouens** [comment]
Realistically, I think it’d be fine to have it be a global setting, but there are probably those who’d disagree.  If it’s comparable effort to have it be 2 different settings, that’d be nice.

From: Daniel Nguyen ***@***.***>
Date: Friday, April 12, 2024 at 8:58 AM
To: BoltAI/BoltAI ***@***.***>
Cc: Kenneth Youens ***@***.***>, Mention ***@***.***>
Subject: Re: [BoltAI/BoltAI] Font size in text entry boxes does not obey font size settings (Issue #65)

Thank you. Quick question, @kyouens<https://github.com/kyouens>, would you prefer to use the same font size for both input text and the chat bubble text, or would you prefer them to be 2 different settings?

**Comment by longseespace** [comment]
I'm working on this and the result is... interesting. It looks pretty bad 😅

![CleanShot 2024-04-24 at 00 11 43@2x](https://github.com/BoltAI/BoltAI/assets/187720/8783479f-a90d-4139-a997-898ca188278d)

![CleanShot 2024-04-24 at 00 11 30@2x](https://github.com/BoltAI/BoltAI/assets/187720/396a79e1-178e-43a9-84f0-0f80afe8845e)

**Comment by longseespace** [comment]
Yeah I think it looks ok if the font is not too large 

![CleanShot 2024-04-24 at 00 47 40@2x](https://github.com/BoltAI/BoltAI/assets/187720/9b5bb7cb-4876-4580-a26a-f92050bc9028)

**Comment by kyouens** [comment]
Agree

From: Daniel Nguyen ***@***.***>
Date: Tuesday, April 23, 2024 at 12:48 PM
To: BoltAI/BoltAI ***@***.***>
Cc: Kenneth Youens ***@***.***>, Mention ***@***.***>
Subject: Re: [BoltAI/BoltAI] Font size in text entry boxes does not obey font size settings (Issue #65)

Yeah I think it looks ok if the font is not too large

***@***.*** (view on web)<https://github.com/BoltAI/BoltAI/assets/187720/9b5bb7cb-4876-4580-a26a-f92050bc9028>

**Comment by longseespace** [comment]
I've added this in v1.15.16 https://boltai.canny.io/changelog/v11516-build-59.
