### ISSUE TITLE
DALL E 3 doesn't work after valid API key added

### ISSUE THREAD

**Issue by drparker48** [BoltAI/BoltAI#66]
The DALL E 3 doesn't work even after entering a valid API key from OpenAI - It just keeps asking for an API key to use the model.

**Comment by drparker48** [comment]
Hi Daniel

Thanks for your quick reponse.

Yes, I am using BoltAI via Setapp and I’m generating the API key using the link within BoltAI.

I have tried restarting the app and restarting the Mac to no avail. The API is funded and I’m not getting that common error with using OpenAI keys.

No error is being flagged but I suspect the API key I am entering isn’t being saved as the key isn’t there if I go back to enter it again?

David

**Comment by longseespace** [comment]
Can you go to Settings > Model and check if the API key was there. Don't forget to click save.

![CleanShot 2024-04-12 at 22 32 23@2x](https://github.com/BoltAI/BoltAI/assets/187720/3c657fd9-28dd-4433-9188-3a762deae65c)

**Comment by longseespace** [comment]
I think I figured out what's wrong. You might need to start a new chat. You won't be able to use the (Example) chat. @drparker48

**Comment by drparker48** [comment]
Thanks, Daniel - that was it, I needed to start a new chat. I did check the setting as you suggested and that was fine. Maybe you need to prompt users to start a new chat after an API key is saved.

Thanks again

David

**Comment by longseespace** [comment]
Thanks. I've added the notice.
