### ISSUE TITLE
Chat list disappearing on large inputs

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#7]
https://github.com/BoltAI/BoltAI/assets/77480421/c9ed5297-339d-4543-8018-2289d5ca9837

On very large inputs, the chat list on the left keeps shifting up. 

One very simple solution could be to cap the max height of the input box and if the input exceeds that height, the textbox becomes scrollable.

Not shown in the video but a better way to reproduce this could be to reach the limit at which the bug starts to occur, then keep adding lines one by one to see the chat list keep going out of bounds gradually

**Comment by longseespace** [comment]
I've fixed this in v1.10 https://boltai.com/changelogs/v1.10. Feel free to reopen the issue if it still persists.
