### ISSUE TITLE
Limit Reached Message Until Restart After Topping Up API Credits

### ISSUE THREAD

**Issue by blankster** [BoltAI/BoltAI#70]
I noticed a small error that occurs when the OpenAI API limits are reached. BoltAI then correctly reports back and refers to the correct URL (which should still be clickable for it to be perfect, that would be very useful).

However, if one then balances out the available amount accordingly, the same error message is still given.

But if you restart BoltAI, then everything works again as it should.

So, it seems there is a constellation in which the OpenAI API is not queried correctly anymore, but just the error message is reported back. I can't explain it any other way than that it immediately worked again once BoltAI was restarted and the API was queried again correctly.

If this depends on the type of shortcut, I used a text-replacement shortcut. In my case, it wasn't project/global limits, but it was a negative amount here:

![CleanShot 2024-04-20 at 12 45 56](https://github.com/BoltAI/BoltAI/assets/1443109/2a881f75-baf5-441c-9137-6e6a128e4050)

I hope this report helps to squash this little 🐛.

**Comment by longseespace** [comment]
I think there is a delay between the time you topped up your account and when they re-activate your API key. This happened to me and a few other customers. I guess the "restart" was just a coincident :D
