### ISSUE TITLE
Command N and "Quick Chat" do not open a quick chat

### ISSUE THREAD

**Issue by AstroCodeCat** [BoltAI/BoltAI#73]
I can see the file menu briefly highlight but no window pops up. I need to shut down and relaunch boltAI. Looks like it happens if I have closed the windows using command W. Doesn't seem to be a way to open the main again. Suggest if no main window open when someone presses, then you open one. 

I, like many mac users, use the command W a lot to close windows, especially browser tabs.

FYI - I am loving your app and am very impressed. Looking forward to it developing further and adding more user interface enhancements. I can see this becoming central to my workflow if I can operate it smoothly with shortcuts and integrations. Thank you for your efforts (came to you from setapp)

**Comment by longseespace** [comment]
This has been fixed in v1.15.16 https://boltai.canny.io/changelog/v11516-build-59. Feel free to reopen if it doesn't work for you.

**Comment by AstroCodeCat** [comment]
Amazing - thanks for your super fast repsonse and fix.

**Comment by AstroCodeCat** [comment]
Daniel,

Thanks for fixing this and your super fast response. Very much appreciated.

Thanks

Mike

From: Daniel Nguyen ***@***.***>
Reply to: BoltAI/BoltAI ***@***.***>
Date: Wednesday, 24 April 2024 at 4:32 AM
To: BoltAI/BoltAI ***@***.***>
Cc: Mike Tyldesley ***@***.***>, Author ***@***.***>
Subject: Re: [BoltAI/BoltAI] Command N and "Quick Chat" do not open a quick chat (Issue #73)


This has been fixed in v1.15.16 https://boltai.canny.io/changelog/v11516-build-59. Feel free to reopen if it doesn't work for you.
