### ISSUE TITLE
Bug: Font for Responses

### ISSUE THREAD

**Issue by topherolson** [BoltAI/BoltAI#76]
When you change the font in the setting it only changes for messages you sent, not the responses by the LLMs. 

![Screenshot 2024-04-25 at 09 47 32](https://github.com/BoltAI/BoltAI/assets/868769/6e9602d8-a8ed-4ec6-ae55-7ca992b184e2)

**Comment by longseespace** [comment]
This is fixed. Can you confirm? (feel free to reopen the ticket if not)

**Comment by topherolson** [comment]
Yep! Working great.
