### ISSUE TITLE
Scrolling is incredibly slow/laggy

### ISSUE THREAD

**Issue by btglr** [BoltAI/BoltAI#8]
Scrolling with the touchpad is incredibly slow, and scrolling by picking up the scrollbar is very glitchy. Scrolling with a mouse works fine though.

**Comment by SilverMarcs** [comment]
For me scrolling with trackpad is quite laggy too. Turning off markdown rendering makes it very slightly better but still quite laggy

**Comment by longseespace** [comment]
Thanks for the input. The technical side of it is I'm using `LazyVStack` for the view and its performance is not good with a large amount of text.

I've been working on a rewrite for it, using the more performant `NSTableView` instead.

**Comment by longseespace** [comment]
I've improved this in v1.10 https://boltai.com/changelogs/v1.10. Feel free to reopen the issue if it still persists.
