### ISSUE TITLE
Claude Constant Timeouts

### ISSUE THREAD

**Issue by bwt615** [BoltAI/BoltAI#81]
Is there a threshold to increase? This is like 95% of my larger requests:

![CleanShot 2024-05-01 at 23 31 29](https://github.com/BoltAI/BoltAI/assets/48396397/073580e4-79f0-49f8-9fdc-548a2a5f99f9)

**Comment by longseespace** [comment]
You can increase network time out in Settings > Advanced > Network.

![CleanShot 2024-05-02 at 10 41 55@2x](https://github.com/BoltAI/BoltAI/assets/187720/f716caee-46f9-45d4-bfc3-630f26934d18)

**Comment by bwt615** [comment]
I upped this to 5 min, it doesn't seem to be respecting it.

**Comment by longseespace** [comment]
Actually you're right, sorry. The configuration applies for other services but not Anthropic. Releasing a fix in a a few minutes.

**Comment by bwt615** [comment]
I forgot to reply I had gotten around it by disabling tools which re-enabled streaming!

Thank you!! I'll keep the feedback coming :)

**Comment by longseespace** [comment]
Thanks. I've released the fix for network timeout configuration (v1.15.19)
