### ISSUE TITLE
Whitespace not preserved in agent messages

### ISSUE THREAD

**Issue by jnordberg** [BoltAI/BoltAI#82]
Whitespace is not rendered correctly in agent messages.

<img width="860" alt="Screenshot 2024-05-07 at 15 05 09" src="https://github.com/BoltAI/BoltAI/assets/95886/171736de-9264-49c5-b415-acdddac3e3b6">

When copying using the copy button the text is:
```
Snowflakes gently fall
Blanketing the winter scene
Peaceful silence deep
```

This can be very annoying with models that don't always output markdown, what OpenAI does (I think) is to classify the output and switch to a markdown parser if it's above some threshold. You can see it switch render mode sometimes.

I'd be happy with a setting to just render text as-is though.

**Comment by longseespace** [comment]
Hi @jnordberg, you can disable the Markdown renderer in View > Markdown menu. Or you can also do so in Settings > General.

Would that work for you?

**Comment by jnordberg** [comment]
Nice! yes that works for me 🙌
