### ISSUE TITLE
Groq support is broken

### ISSUE THREAD

**Issue by dmatora** [BoltAI/BoltAI#83]
Can not save API key after model list has changed on server
<img width="912" alt="image" src="https://github.com/BoltAI/BoltAI/assets/647062/6bde8ced-9874-4132-a772-2299ea9701eb">

**Comment by longseespace** [comment]
Hi @dmatora, can you try manually change the Default Model to something else and try again? Maybe the model was under high load.

I was able to save it without issue though.

**Comment by dmatora** [comment]
Tried different models, tried downgrading app and importing settings from old Mac, nothing helps

**Comment by longseespace** [comment]
I tend to think there was an issue with your api key or the connection. Do you mind sharing your API key with me so I could debug further? You can revoke access later in Groq Dashboard.

Either join our Discord (https://boltai.com/discord) or via email (daniel at boltai.com)

**Comment by dmatora** [comment]
You were right (well, very close). This issue was broken internet connection. Once I fixed that it started working with both old/new list of models.
