### ISSUE TITLE
Incorrect Model Selection When Creating a New Chat with GPT-4o

### ISSUE THREAD

**Issue by chuducandev** [BoltAI/BoltAI#85]
### Description

I have set GPT-4o as my default model in the application settings. However, every time I create a new chat, the app automatically selects the GPT-3.5 model instead of the GPT-4o model. This forces me to manually switch to GPT-4o using the top bar for each new conversation, which is inconvenient and time-consuming.

### Steps to Reproduce

- Set GPT-4o as the default model in the application settings.
- Create a new chat.
- Observe that the app selects GPT-3.5 instead of GPT-4o.

### Expected Behavior

When creating a new chat, the app should automatically select GPT-4o, as it is set as the default model.

### Actual Behavior

The app selects GPT-3.5, requiring manual selection of GPT-4o for each new chat.

### Impact

This issue causes inconvenience and interruptions in workflow, as users must repeatedly change the model to GPT-4o.

### Environment

App Version: 1.15.21 (build 64)
Operating System: macOS Sonoma 14.4.1
Device: MacBook Pro 14 M1 Pro (Base model)

**Comment by longseespace** [comment]
Yeah this has been fixed in v1.15.22. Can you confirm?

Thanks

**Comment by kevinseabourne** [comment]
when you upload images the model reverts back to gtp-4-turbo

**Comment by longseespace** [comment]
> when you upload images the model reverts back to gtp-4-turbo

Ah yeah. There were only 2 vision models previously so it automatically switch back to that one. Will fix today!

**Comment by longseespace** [comment]
It's been fixed in the latest version `v1.15.24`. Feel free to reopen the issue. Thanks.

**Comment by chuducandev** [comment]
> Yeah this has been fixed in v1.15.22. Can you confirm?
> 
> Thanks

Confirmed. It works as expected in v[REDACTED]. Thanks for fixing the bug.
