### ISSUE TITLE
GPT-4o Image Generation Not Displaying

### ISSUE THREAD

**Issue by feassarian** [BoltAI/BoltAI#86]
With a prompt requiring a photo to be generated, the response includes the appropriate heading for the photo, but only presents a blue question mark box.

Right click download or open in new window do not do anything
<img width="650" alt="Screenshot 2024-05-14 at 10 13 55 AM" src="https://github.com/BoltAI/BoltAI/assets/63697704/4f25dc52-843b-4f76-ac8f-e1df01072ed7">

**Comment by longseespace** [comment]
Oh I haven’t thought about this scenario. Any chance you can share your prompts so I could fix it faster. Thanks

**Comment by feassarian** [comment]
Sure thing...

"Using the provided link, create a blog post of 1000-1500 words.  Additionally, suggest a photo for the blog post, a headline title, a 250 character or less summary and social media posts for Facebook and LinkedIn to accompany the blog post."

Add any website you want to the end of the prompt

Using OpenAI GPT-4o

**Comment by longseespace** [comment]
Thanks. In my test, the image doesn't exist that why it show the blue question mark.

Can you disable the markdown renderer to see the real image URL?

![CleanShot 2024-05-15 at 11 54 07@2x](https://github.com/BoltAI/BoltAI/assets/187720/9d4bb9ff-af53-49d5-b1e5-f06f3e0f5ef8)

**Comment by longseespace** [comment]
Side note: I don't think GPT-4o has the capability to generate images. In ChatGPT app, I think they use Dall E 3 under the hood.

**Comment by feassarian** [comment]
Interesting - I turned off the markdown and it provided a URL - but the URL still goes out to a 404 - wonder if this is a type of hallucination?

Side note - previously with gpt-4 Turbo - the same prompt would return a description of a suggested photo - which as you pointed out - I usually then fed into Dall.  Its interesting the gpt-4o is attempting to resolve/generate the actual picture - even though its failing.

**Comment by longseespace** [comment]
Yeah I think the model hallucinated.

**Comment by longseespace** [comment]
I'm closing this as currently, the 4o model doesn't support image generation yet.
