### ISSUE TITLE
[BUG] In “Setapp OpenAI Service” settings, Default Model doesn’t save

### ISSUE THREAD

**Issue by inspiredearth** [BoltAI/BoltAI#87]
I’m using BoltAI via Setapp subscription.

In the Models preferences, the Default Model is always blank. If I select a model in the drop down, and leave that tab, etc., it is blank again when I return. It seems to default to GPT-4 Turbo. I want to set the default to GPT-4o. But I can’t for this reason.

![CleanShot 2024-05-21 at 21 14 24](https://github.com/BoltAI/BoltAI/assets/667395/9bf82103-3728-4151-96fe-e6b992e2370f)

**Comment by longseespace** [comment]
Thanks. I will release a new version very soon.

**Comment by longseespace** [comment]
This has been fixed. Can you confirm, thanks.
