### ISSUE TITLE
How to modify the maximum token limit of Setapp? I used a custom model, but still subject to this restriction, which doesn't seem reasonable.

### ISSUE THREAD

**Issue by ddhjy** [BoltAI/BoltAI#88]
How to modify the maximum token limit of Setapp? I used a custom model, but still subject to this restriction, which doesn't seem reasonable.

**Comment by longseespace** [comment]
This sounds like a bug to me. What is your current setup?

**Comment by longseespace** [comment]
Hello @ddhjy, any chance you can share with me the issue details?

**Comment by longseespace** [comment]
I think this has been fixed. Feel free to reopen the issue.
