### ISSUE TITLE
Unable to edit a previous message

### ISSUE THREAD

**Issue by SilverMarcs** [BoltAI/BoltAI#9]
When I got back 2-3 messages and want to edit my own message, clicking on the edit button does nothing. Expected behaviour is to edit the message and then start regenerating again from that point onwards, similar to what happens on Chatgpt web ui.

One workaround for now is to delete the newer messages upto the message i want to delete and then it enables me to edit it but that is not ideal.

**Comment by longseespace** [comment]
Hi @SilverMarcs, I've been trying to replicate your issue but wasn't able to.

Does it still happen? Which OS are you on?

**Comment by SilverMarcs** [comment]
Sonoma.

To add more info, it seems the edit button works sometimes but doesnt on other times. Couldnt pinpoint the exact cases that make it behave like this. sometimes I click an edit button that didnt work. I go back some messages, click edit button (with failure), return to the initial message, and its edit button works. But this is totally random, couldn't find a pattern here either.

After sending a message, the edit box does pop up. if multiple messages' edit buttons were clicked, then edit boxes for all of them start to show up one after the other if I am pressing Esc button to dismiss them.

I think the problem is more prone to show up on older chats that havent been used in a while, but again, I can't definitively say this since no fixed pattern.
