### ISSUE TITLE
Selecting text in conversation prompts not possible

### ISSUE THREAD

**Issue by MichaelPietroforte** [BoltAI/BoltAI#93]
I can select and copy text from responses, but I can't do the same for previous prompts. The only way to do this is to edit the prompt, which is quite cumbersome. I frequently copy text from a previous prompt for a new one. This is why I prefer using the OpenAI app for longer conversations.

**Comment by longseespace** [comment]
Yeah, this is a known issue. Enabling text selection crashes the app for some users and I haven't found a good workaround yet.

Maybe I can make it an option and if yours is not crash, you can enable it.

Reference about the crash: https://x.com/daniel_nguyenx/status/1785002634774241475

**Comment by MichaelPietroforte** [comment]
Hi Daniel,

Thank you for the prompt response. It's highly unlikely that enabling text selection is the actual cause of the issue, or that Swift has such a bug. It's more probable that there is a conflict with other parts of your code or with a third-party app used by these users. Have you been able to replicate the issue?

Disabling text selection is not a solution, as it is a major downside of BoltAI compared to other AI apps. I would certainly appreciate it if you enabled this feature.

Thanks,
Michael

**Comment by longseespace** [comment]
>  It's highly unlikely that enabling text selection is the actual cause of the issue, or that Swift has such a bug. It's more probable that there is a conflict with other parts of your code or with a third-party app used by these users. Have you been able to replicate the issue?

Yes. Took me a few days and it is, in fact, the text selection was the culprit.

You would be amaze by the number of bugs in `SwiftUI` framework haha.

I've added a feature flag for this and will release a new version soon.

https://x.com/daniel_nguyenx/status/1797175113433137478

**Comment by longseespace** [comment]
Hi @MichaelPietroforte, I've released v1.16.0 with 20+ new features, including the workaround for this.

You can enable text selection with this: https://boltai.com/docs/troubleshooting/cant-select-text-in-conversation-prompt

Can you give it a try and le me know if it works for you

**Comment by MichaelPietroforte** [comment]
Thanks! Works great! No crashes here.

I love the new Perplexity search feature! Hopefully, their API will support integrating references into the responses soon.

However, your new version seems to have a serious bug. "Enter to send message" often doesn't work. When I press enter, the message disappears without being sent. It usually starts working for some time after restarting the app. The Send message icon always works.

Another thing that does not work is searching your documentation. I tried Safari and Chrome
