### ISSUE TITLE
Models loading delays

### ISSUE THREAD

**Issue by woestler** [BoltAI/BoltAI#99]
When initiating a new conversation, the API service and model are always loading, which takes a long time, and this issue has a high frequency of occurrence.

![Screenshot](https://github.com/BoltAI/BoltAI/assets/4202999/4df31a57-7441-46e3-a7c7-a98eebc47670)

**Comment by longseespace** [comment]
I'm taking a deeper look now. Are you on macOS 12? @woestler  :D

**Comment by longseespace** [comment]
I've fixed this in v1.16.1. Please update. Thanks :D

**Comment by longseespace** [comment]
Feel free to re-open the ticket if the problem still persists.
